In [1]:
import matplotlib.pyplot as plt
import seaborn as sns
sns.set(font_scale=2.2,style='white')
import pandas as pd
import numpy as np
import scipy
import pickle as pkl
from collections import OrderedDict

In [2]:
with open('df_unified_20211009.pkl', 'rb') as f:
    df = pkl.load(f)

In [3]:
def get_heat_over_389_participants(df):
    test_df = df[pd.to_numeric(df.quest_heat, errors='coerce').notnull()]
    test_df['quest_heat_numeric'] = pd.to_numeric(test_df['quest_heat'])
    heat_over_389_rows = test_df.where(test_df['quest_heat_numeric'] > 38.9).where(test_df['quest_heat_numeric'] < 41).dropna(how='all')
    return list(heat_over_389_rows.index)

In [4]:
heat_over_389_participants = get_heat_over_389_participants(df)

for part in heat_over_389_participants:
    df.loc[part, "quest_symptoms"] = df.loc[part, "quest_symptoms"] + ',heat over 38.9'

<ipython-input-3-f77aac9f8aab>:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  test_df['quest_heat_numeric'] = pd.to_numeric(test_df['quest_heat'])

In [5]:
df[['date','first_dose_date', 'second_dose_date', 'third_dose_date']].tail()

,date,first_dose_date,second_dose_date,third_dose_date
48899,2021-09-23 00:00:00,2021-01-05 19:30:00,2021-01-28 18:00:00,2021-09-22 08:35:00
59978,2021-09-23 00:00:00,NaN,NaN,2021-09-19 12:00:00
71234,2021-09-23 00:00:00,NaN,NaN,2021-09-18 12:37:00
93102,2021-09-23 00:00:00,2021-01-04 16:00:00,2021-01-25 16:00:00,2021-09-17 11:11:00
67318,2021-09-23 00:00:00,NaN,NaN,2021-09-23 12:35:00

In [6]:
df[['days_from_q_to_first',
       'hours_from_q_to_first', 'days_from_q_to_second',
       'hours_from_q_to_second', 'days_from_q_to_third',
       'hours_from_q_to_third']].tail()

,days_from_q_to_first,hours_from_q_to_first,days_from_q_to_second,hours_from_q_to_second,days_from_q_to_third,hours_from_q_to_third
48899,260.0,6251.453333,237.0,5700.953333,0.0,22.370000
59978,NaN,NaN,NaN,NaN,3.0,91.503056
71234,NaN,NaN,NaN,NaN,4.0,116.392778
93102,261.0,6281.548056,240.0,5777.548056,5.0,142.364722
67318,NaN,NaN,NaN,NaN,-1.0,-2.948333

In [7]:
df[['quest_sleep_time', 'quest_sleep_quality',
       'quest_sport_time', 'quest_meetings', 'quest_mood', 'quest_stress',
       'quest_symptoms', 'quest_diagnosis', 'quest_other_symptoms',
       'quest_heat', 'quest_other_diagnosis']].tail()

,quest_sleep_time,quest_sleep_quality,quest_sport_time,quest_meetings,quest_mood,quest_stress,quest_symptoms,quest_diagnosis,quest_other_symptoms,quest_heat,quest_other_diagnosis
48899,6.5,0.0,0.0,6.0,-1.0,1.0,weakness,healthy,NaN,NaN,NaN
59978,7.0,1.0,45.0,5.0,1.0,-1.0,healthy,healthy,NaN,NaN,NaN
71234,5.0,1.0,180.0,3.0,1.0,-1.0,weakness,healthy,NaN,NaN,NaN
93102,7.0,1.0,30.0,10.0,1.0,-1.0,healthy,healthy,NaN,NaN,NaN
67318,4.0,0.0,10.0,11.0,0.0,0.0,healthy,healthy,NaN,NaN,NaN

In [15]:
vaccines_to_analyze = ['days_from_q_to_first', 'days_from_q_to_second', 'days_from_q_to_third']

In [16]:
vaccine_labels = ['First Vaccination', 'Second Vaccination', 'Third Vaccination']

In [17]:
symptoms_dfs = [df[(df[v]<=7)&(df[v]>=-7)][['participant_num', 'quest_symptoms', v]] for v in vaccines_to_analyze]

In [18]:
for i in range(len(vaccine_labels)):
    print("%s n= %d" % (vaccine_labels[i], symptoms_dfs[i]["participant_num"].nunique()))

First Vaccination n= 244
Second Vaccination n= 386
Third Vaccination n= 1443

In [19]:
for symptoms_df in symptoms_dfs:
    symptoms_df["quest_symptoms_processed"] = symptoms_df["quest_symptoms"].replace({'-1': '',
                                                                             'skipped_question': '',
                                                                             np.nan: ''}, regex=True)

In [20]:
# Add helper methods and objects

#First, categorize heat and fever into > 38.9 and <= 38.9
#Severe: ['chest_pain', 'dyspnea', 'heat over 38.9', 'confusion', 'chills']
 
#Mild: everything else: ['abdominal_pain', 'feel_heat', 'heat_over_37.5', 'back_or_neck_pain', 'cold', 'muscles_pain', 'weakness', 'headache',
#'dizziness', 'vomiting', 'sore_throat', 'diarrhea', 'cough', 'hand_muscles_pain', 'leg_pain', 'ear_pain', 'taste_smell', 'lymph',
# 'fast_heartbeat', 'hypertension']


symp_titles = {'healthy':'No\n Reaction',
               'chest_pain': 'Chest\n Pain',
               'dyspnea':'Dyspnea',
               'heat over 38.9':'Fever\n >38.9',
               'confusion':'Confusion',
               'chills':'Chills',
               'abdominal_pain':'Muscle\n Pain',
               'feel_heat':'Fever\n <=38.9',
               'heat over 37.5':'Fever\n <=38.9',
               'back_or_neck_pain':'Muscle\n Pain',
               'cold':'Cold',
               'muscles_pain':'Muscle\n Pain',
               'weakness':'Fatigue',
               'headache':'Headache',
               'dizziness':'Dizziness',
               'vomiting':'Vomiting',
               'sore_throat':'Sore\n Throat',
               'diarrhea':'Diarrhea',
               'cough':'Cough',
               'hand_muscles_pain':'Muscle\n Pain',
               'leg_pain':'Muscle\n Pain',
               'ear_pain':'Muscle\n Pain',
               'taste_smell':'Loss of\nTaste/Smell',
               'lymph':'Lymph',
               'fast_heartbeat':'Fast Heartbeat',
               'hypertension':'Hypertension',
               'other':'Other',
              '' : 'Skipped Questionnaire'}

possible_symptoms = symp_titles.keys()

def classify_heat(heat_str):
    heat_array = heat_str.split(':')
    if heat_array[0] != 'heat':
        return ""
    try:
        temp = float(heat_array[1])
        # One person made a typo, heat is 636.6
        if temp >= 300:
            temp = temp - 600
        # A couple people did not report 30 with their heat, e.g. reporting 6.4 instead of 36.4
        if temp <= 10:
            temp = temp + 30
            
        if temp <= 30 or temp >= 41:
            return "error with heat %.2f" % (temp)
        
        if temp > 38.9:
            return "heat over 38.9"
        if temp > 37.5:
            return "heat over 37.5"
        else:# temp >= 35:
            return "no heat"
    # If the heat could not be converted to float, assume person is healthy
    except:
        return "no heat"

def preprocess_symptom_array(arr):
    arr = arr.copy()
    for i in range(len(arr)):
        s = arr[i]
        if "heat:" in s:
            arr[i] = classify_heat(s)
    return list(set(arr))

In [21]:
# Assert that all symptoms are accounted for in the symptoms listed
# in the above dictionary or by processing their heat entry

for symptoms_df in symptoms_dfs:
    for i,r in symptoms_df.iterrows():
        symptoms = r["quest_symptoms_processed"].split(',')
        for symptom in symptoms:
            #print(symptoms)
            assert((symptom in possible_symptoms)
                   or (classify_heat(symptom) in possible_symptoms)
                   or (classify_heat(symptom) == 'no heat'))

In [22]:
# Create baseline and make sure that those who reported symptoms
# in days [-7,...,-1] don't have the same symptom reported for day 0

def create_participant_to_symptoms_before_vaccine_dict(vaccine_num):
    days_since_vaccine = vaccines_to_analyze[vaccine_num]
    symptoms_df = symptoms_dfs[vaccine_num]
    
    part_to_symptoms_before_vaccine = dict()

    df = symptoms_df.where(symptoms_df[days_since_vaccine]<=-1).dropna(how='all')
    df = df.where(df["quest_symptoms_processed"] != '').dropna(how='all').drop_duplicates('participant_num', keep='last')

    for i,r in df.iterrows():
        symptoms_old = r["quest_symptoms_processed"].split(',')
        symptoms = preprocess_symptom_array(symptoms_old)


        participant = r["participant_num"]

        if symptoms == [''] or symptoms == ['skipped_question'] or symptoms == ['-1']:
            part_to_symptoms_before_vaccine[participant] = []
        elif 'healthy' in symptoms or symptoms == ['no heat']:
            part_to_symptoms_before_vaccine[participant] = []
        else:
            actual_symptoms = list()

            for s in symptoms:
                if s == 'no heat':
                    part_to_symptoms_before_vaccine[participant] = []
                    break
                elif s in possible_symptoms and s != '':
                    actual_symptoms.append(s)

            part_to_symptoms_before_vaccine[participant] = actual_symptoms

        print("Participant %s Symptoms %s => %s" % (participant, symptoms, part_to_symptoms_before_vaccine[participant]))
    return part_to_symptoms_before_vaccine

In [23]:
part_to_sbv_dicts = [create_participant_to_symptoms_before_vaccine_dict(i) for i in range(3)]

Participant p1_152 Symptoms ['healthy'] => []
Participant p1_3 Symptoms ['headache'] => ['headache']
Participant p1_23 Symptoms ['healthy'] => []
Participant 73 Symptoms ['healthy'] => []
Participant p1_296 Symptoms ['healthy'] => []
Participant p1_226 Symptoms ['healthy'] => []
Participant p1_123 Symptoms ['healthy'] => []
Participant p1_32 Symptoms ['other'] => ['other']
Participant 7 Symptoms ['other'] => ['other']
Participant p1_31 Symptoms ['healthy'] => []
Participant p1_28 Symptoms ['healthy'] => []
Participant p1_24 Symptoms ['healthy'] => []
Participant p1_132 Symptoms ['healthy'] => []
Participant 59 Symptoms ['healthy'] => []
Participant 83 Symptoms ['sore_throat'] => ['sore_throat']
Participant 115 Symptoms ['healthy'] => []
Participant 75 Symptoms ['healthy'] => []
Participant p1_22 Symptoms ['healthy'] => []
Participant p1_21 Symptoms ['healthy'] => []
Participant p1_6 Symptoms ['healthy'] => []
Participant p1_144 Symptoms ['healthy'] => []
Participant 57 Symptoms ['healthy'] => []
Participant 27 Symptoms ['healthy'] => []
Participant p1_25 Symptoms ['healthy'] => []
Participant p1_211 Symptoms ['healthy'] => []
Participant p1_130 Symptoms ['healthy'] => []
Participant 112 Symptoms ['healthy'] => []
Participant 104 Symptoms ['healthy'] => []
Participant 89 Symptoms ['healthy'] => []
Participant p1_143 Symptoms ['healthy'] => []
Participant p1_137 Symptoms ['healthy'] => []
Participant p1_121 Symptoms ['healthy'] => []
Participant 48 Symptoms ['healthy'] => []
Participant p1_122 Symptoms ['healthy'] => []
Participant 21 Symptoms ['healthy'] => []
Participant p1_134 Symptoms ['healthy'] => []
Participant p1_126 Symptoms ['healthy'] => []
Participant p1_231 Symptoms ['weakness'] => ['weakness']
Participant 23 Symptoms ['healthy'] => []
Participant 2 Symptoms ['healthy'] => []
Participant 133 Symptoms ['healthy'] => []
Participant 53 Symptoms ['healthy'] => []
Participant p1_109 Symptoms ['healthy'] => []
Participant p1_105 Symptoms ['healthy'] => []
Participant 41 Symptoms ['healthy'] => []
Participant p1_27 Symptoms ['healthy'] => []
Participant p1_108 Symptoms ['healthy'] => []
Participant p1_125 Symptoms ['healthy'] => []
Participant p1_115 Symptoms ['healthy'] => []
Participant 24 Symptoms ['cold'] => ['cold']
Participant p1_114 Symptoms ['healthy'] => []
Participant p1_265 Symptoms ['headache', 'weakness', 'muscles_pain', 'vomiting'] => ['headache', 'weakness', 'muscles_pain', 'vomiting']
Participant p1_153 Symptoms ['healthy'] => []
Participant p1_118 Symptoms ['healthy'] => []
Participant p1_39 Symptoms ['healthy'] => []
Participant 134 Symptoms ['healthy'] => []
Participant p1_4 Symptoms ['healthy'] => []
Participant 147 Symptoms ['healthy'] => []
Participant 142 Symptoms ['healthy'] => []
Participant 76 Symptoms ['healthy'] => []
Participant p1_141 Symptoms ['healthy'] => []
Participant p1_147 Symptoms ['healthy'] => []
Participant 3 Symptoms ['healthy'] => []
Participant 43 Symptoms ['healthy'] => []
Participant p1_155 Symptoms ['healthy'] => []
Participant p1_129 Symptoms ['weakness', 'dyspnea', 'diarrhea'] => ['weakness', 'dyspnea', 'diarrhea']
Participant 38 Symptoms ['healthy'] => []
Participant 1 Symptoms ['healthy'] => []
Participant p1_237 Symptoms ['healthy'] => []
Participant p1_19 Symptoms ['healthy'] => []
Participant p1_8 Symptoms ['healthy'] => []
Participant 46 Symptoms ['healthy'] => []
Participant p1_37 Symptoms ['healthy'] => []
Participant 113 Symptoms ['healthy'] => []
Participant 50 Symptoms ['weakness'] => ['weakness']
Participant p1_26 Symptoms ['cough'] => ['cough']
Participant p1_102 Symptoms ['healthy'] => []
Participant 6 Symptoms ['healthy'] => []
Participant p1_29 Symptoms ['healthy'] => []
Participant p1_303 Symptoms ['healthy'] => []
Participant p1_103 Symptoms ['healthy'] => []
Participant p1_30 Symptoms ['other'] => ['other']
Participant 132 Symptoms ['healthy'] => []
Participant p1_34 Symptoms ['healthy'] => []
Participant 37 Symptoms ['healthy'] => []
Participant 84 Symptoms ['healthy'] => []
Participant 56 Symptoms ['healthy'] => []
Participant p1_300 Symptoms ['healthy'] => []
Participant p1_15 Symptoms ['healthy'] => []
Participant p1_17 Symptoms ['healthy'] => []
Participant p1_101 Symptoms ['healthy'] => []
Participant 32 Symptoms ['healthy'] => []
Participant 47 Symptoms ['healthy'] => []
Participant 86 Symptoms ['healthy'] => []
Participant 136 Symptoms ['weakness'] => ['weakness']
Participant p1_14 Symptoms ['healthy'] => []
Participant 18 Symptoms ['healthy'] => []
Participant 108 Symptoms ['healthy'] => []
Participant 70 Symptoms ['healthy'] => []
Participant p1_145 Symptoms ['healthy'] => []
Participant 121 Symptoms ['healthy'] => []
Participant 130 Symptoms ['healthy'] => []
Participant 143 Symptoms ['healthy'] => []
Participant p1_230 Symptoms ['healthy'] => []
Participant p1_20 Symptoms ['healthy'] => []
Participant 99 Symptoms ['healthy'] => []
Participant p1_149 Symptoms ['healthy'] => []
Participant 26 Symptoms ['healthy'] => []
Participant 82 Symptoms ['healthy'] => []
Participant p1_206 Symptoms ['healthy'] => []
Participant p1_106 Symptoms ['healthy'] => []
Participant 96 Symptoms ['healthy'] => []
Participant 67 Symptoms ['healthy'] => []
Participant p1_238 Symptoms ['healthy'] => []
Participant 161 Symptoms ['healthy'] => []
Participant p1_124 Symptoms ['healthy'] => []
Participant 54 Symptoms ['healthy'] => []
Participant 149 Symptoms ['healthy'] => []
Participant p1_131 Symptoms ['healthy'] => []
Participant p1_16 Symptoms ['healthy'] => []
Participant 8 Symptoms ['cough', 'muscles_pain', 'headache'] => ['cough', 'muscles_pain', 'headache']
Participant p1_157 Symptoms ['healthy'] => []
Participant 71 Symptoms ['cold'] => ['cold']
Participant 102 Symptoms ['healthy'] => []
Participant 120 Symptoms ['healthy'] => []
Participant p1_151 Symptoms ['healthy'] => []
Participant 80 Symptoms ['healthy'] => []
Participant 154 Symptoms ['healthy'] => []
Participant p1_250 Symptoms ['healthy'] => []
Participant p1_287 Symptoms ['healthy'] => []
Participant 40 Symptoms ['healthy'] => []
Participant 137 Symptoms ['healthy'] => []
Participant p1_33 Symptoms ['cough', 'diarrhea'] => ['cough', 'diarrhea']
Participant p1_154 Symptoms ['healthy'] => []
Participant p1_266 Symptoms ['cough', 'cold'] => ['cough', 'cold']
Participant 170 Symptoms ['healthy'] => []
Participant p1_119 Symptoms ['healthy'] => []
Participant p1_203 Symptoms ['healthy'] => []
Participant 58 Symptoms ['healthy'] => []
Participant 122 Symptoms ['healthy'] => []
Participant 4 Symptoms ['healthy'] => []
Participant p1_400 Symptoms ['healthy'] => []
Participant 78 Symptoms ['healthy'] => []
Participant 119 Symptoms ['healthy'] => []
Participant 93 Symptoms ['headache'] => ['headache']
Participant 74 Symptoms ['healthy'] => []
Participant 116 Symptoms ['healthy'] => []
Participant 16 Symptoms ['healthy'] => []
Participant 151 Symptoms ['healthy'] => []
Participant p1_402 Symptoms ['healthy'] => []
Participant 95 Symptoms ['healthy'] => []
Participant 35 Symptoms ['healthy'] => []
Participant 39 Symptoms ['healthy'] => []
Participant 114 Symptoms ['healthy'] => []
Participant 144 Symptoms ['healthy'] => []
Participant p1_267 Symptoms ['healthy'] => []
Participant 19 Symptoms ['healthy'] => []
Participant 85 Symptoms ['dyspnea'] => ['dyspnea']
Participant p1_777 Symptoms ['healthy'] => []
Participant 203 Symptoms ['healthy'] => []
Participant 163 Symptoms ['healthy'] => []
Participant 63 Symptoms ['healthy'] => []
Participant 49 Symptoms ['healthy'] => []
Participant p1_411 Symptoms ['healthy'] => []
Participant 209 Symptoms ['healthy'] => []
Participant 34 Symptoms ['diarrhea'] => ['diarrhea']
Participant 153 Symptoms ['healthy'] => []
Participant 152 Symptoms ['healthy'] => []
Participant 101 Symptoms ['healthy'] => []
Participant p1_247 Symptoms ['healthy'] => []
Participant 179 Symptoms ['healthy'] => []
Participant p1_255 Symptoms ['healthy'] => []
Participant 28 Symptoms ['healthy'] => []
Participant 51 Symptoms ['healthy'] => []
Participant 181 Symptoms ['healthy'] => []
Participant 212 Symptoms ['healthy'] => []
Participant 31 Symptoms ['healthy'] => []
Participant p1_254 Symptoms ['healthy'] => []
Participant 162 Symptoms ['healthy'] => []
Participant 68 Symptoms ['healthy'] => []
Participant 166 Symptoms ['healthy'] => []
Participant p1_241 Symptoms ['healthy'] => []
Participant p1_539 Symptoms ['healthy'] => []
Participant p1_540 Symptoms ['cold'] => ['cold']
Participant 36 Symptoms ['healthy'] => []
Participant 182 Symptoms ['healthy'] => []
Participant p1_223 Symptoms ['cold'] => ['cold']
Participant 138 Symptoms ['healthy'] => []
Participant p1_276 Symptoms ['healthy'] => []
Participant 25 Symptoms ['healthy'] => []
Participant 175 Symptoms ['healthy'] => []
Participant p1_561 Symptoms ['healthy'] => []
Participant p1_298 Symptoms ['healthy'] => []
Participant 69 Symptoms ['healthy'] => []
Participant 169 Symptoms ['healthy'] => []
Participant p1_597 Symptoms ['healthy'] => []
Participant p1_244 Symptoms ['other'] => ['other']
Participant 92 Symptoms ['healthy'] => []
Participant 230 Symptoms ['healthy'] => []
Participant p1_590 Symptoms ['healthy'] => []
Participant 275 Symptoms ['cough', 'weakness', 'muscles_pain'] => ['cough', 'weakness', 'muscles_pain']
Participant 329 Symptoms ['healthy'] => []
Participant 247 Symptoms ['healthy'] => []
Participant 198 Symptoms ['healthy'] => []
Participant 187 Symptoms ['healthy'] => []
Participant 110 Symptoms ['healthy'] => []
Participant 340 Symptoms ['healthy'] => []
Participant 603 Symptoms ['cough', 'headache'] => ['cough', 'headache']
Participant 709 Symptoms ['healthy'] => []
Participant 508 Symptoms ['healthy'] => []
Participant 557 Symptoms ['healthy'] => []
Participant 825 Symptoms ['healthy'] => []
Participant 1108 Symptoms ['diarrhea'] => ['diarrhea']
Participant 118 Symptoms ['healthy'] => []
Participant 1617 Symptoms ['sore_throat'] => ['sore_throat']
Participant p1_606 Symptoms ['healthy'] => []
Participant 156 Symptoms ['healthy'] => []
Participant p1_296 Symptoms ['healthy'] => []
Participant p1_123 Symptoms ['healthy'] => []
Participant 73 Symptoms ['healthy'] => []
Participant 210 Symptoms ['healthy'] => []
Participant p1_226 Symptoms ['healthy'] => []
Participant p1_32 Symptoms ['healthy'] => []
Participant 83 Symptoms ['healthy'] => []
Participant 103 Symptoms ['healthy'] => []
Participant p1_24 Symptoms ['healthy'] => []
Participant 109 Symptoms ['healthy'] => []
Participant p1_23 Symptoms ['healthy'] => []
Participant p1_144 Symptoms ['healthy'] => []
Participant p1_3 Symptoms ['headache'] => ['headache']
Participant p1_152 Symptoms ['healthy'] => []
Participant p1_132 Symptoms ['healthy'] => []
Participant 57 Symptoms ['sore_throat'] => ['sore_throat']
Participant p1_31 Symptoms ['healthy'] => []
Participant p1_28 Symptoms ['healthy'] => []
Participant 59 Symptoms ['healthy'] => []
Participant 129 Symptoms ['healthy'] => []
Participant p1_21 Symptoms ['healthy'] => []
Participant p1_22 Symptoms ['healthy'] => []
Participant 164 Symptoms ['healthy'] => []
Participant 112 Symptoms ['healthy'] => []
Participant p1_25 Symptoms ['healthy'] => []
Participant 27 Symptoms ['healthy'] => []
Participant 75 Symptoms ['healthy'] => []
Participant p1_211 Symptoms ['healthy'] => []
Participant p1_237 Symptoms ['healthy'] => []
Participant p1_130 Symptoms ['healthy'] => []
Participant 104 Symptoms ['healthy'] => []
Participant 89 Symptoms ['healthy'] => []
Participant 76 Symptoms ['healthy'] => []
Participant 48 Symptoms ['healthy'] => []
Participant p1_122 Symptoms ['healthy'] => []
Participant p1_115 Symptoms ['healthy'] => []
Participant p1_121 Symptoms ['healthy'] => []
Participant 21 Symptoms ['healthy'] => []
Participant 201 Symptoms ['healthy'] => []
Participant p1_126 Symptoms ['healthy'] => []
Participant p1_143 Symptoms ['healthy'] => []
Participant p1_6 Symptoms ['healthy'] => []
Participant p1_27 Symptoms ['healthy'] => []
Participant 197 Symptoms ['healthy'] => []
Participant p1_134 Symptoms ['healthy'] => []
Participant 133 Symptoms ['healthy'] => []
Participant p1_231 Symptoms ['healthy'] => []
Participant 43 Symptoms ['healthy'] => []
Participant 134 Symptoms ['healthy'] => []
Participant 24 Symptoms ['healthy'] => []
Participant p1_108 Symptoms ['healthy'] => []
Participant p1_109 Symptoms ['healthy'] => []
Participant p1_125 Symptoms ['healthy'] => []
Participant 142 Symptoms ['healthy'] => []
Participant p1_118 Symptoms ['healthy'] => []
Participant p1_153 Symptoms ['healthy'] => []
Participant p1_39 Symptoms ['healthy'] => []
Participant 80 Symptoms ['healthy'] => []
Participant p1_4 Symptoms ['healthy'] => []
Participant p1_105 Symptoms ['healthy'] => []
Participant 2 Symptoms ['healthy'] => []
Participant p1_137 Symptoms ['healthy'] => []
Participant p1_147 Symptoms ['healthy'] => []
Participant p1_265 Symptoms ['ear_pain', 'weakness', 'muscles_pain', 'vomiting'] => ['ear_pain', 'weakness', 'muscles_pain', 'vomiting']
Participant p1_114 Symptoms ['healthy'] => []
Participant 53 Symptoms ['healthy'] => []
Participant p1_155 Symptoms ['healthy'] => []
Participant p1_504 Symptoms ['healthy'] => []
Participant p1_403 Symptoms ['healthy'] => []
Participant 1 Symptoms ['healthy'] => []
Participant 147 Symptoms ['healthy'] => []
Participant 41 Symptoms ['healthy'] => []
Participant p1_407 Symptoms ['healthy'] => []
Participant 183 Symptoms ['healthy'] => []
Participant p1_141 Symptoms ['healthy'] => []
Participant p1_34 Symptoms ['healthy'] => []
Participant p1_129 Symptoms ['weakness', 'cold', 'dyspnea'] => ['weakness', 'cold', 'dyspnea']
Participant p1_8 Symptoms ['healthy'] => []
Participant p1_29 Symptoms ['healthy'] => []
Participant p1_113 Symptoms ['healthy'] => []
Participant p1_406 Symptoms ['healthy'] => []
Participant p1_502 Symptoms ['healthy'] => []
Participant p1_401 Symptoms ['healthy'] => []
Participant 46 Symptoms ['healthy'] => []
Participant p1_26 Symptoms ['cold'] => ['cold']
Participant 204 Symptoms ['healthy'] => []
Participant 50 Symptoms ['healthy'] => []
Participant p1_15 Symptoms ['healthy'] => []
Participant p1_501 Symptoms ['hand_muscles_pain'] => ['hand_muscles_pain']
Participant 47 Symptoms ['healthy'] => []
Participant p1_303 Symptoms ['healthy'] => []
Participant p1_30 Symptoms ['healthy'] => []
Participant 84 Symptoms ['healthy'] => []
Participant p1_103 Symptoms ['healthy'] => []
Participant 136 Symptoms ['healthy'] => []
Participant 23 Symptoms ['healthy'] => []
Participant 3 Symptoms ['healthy'] => []
Participant 132 Symptoms ['healthy'] => []
Participant 32 Symptoms ['cold'] => ['cold']
Participant 56 Symptoms ['healthy'] => []
Participant p1_230 Symptoms ['healthy'] => []
Participant 37 Symptoms ['healthy'] => []
Participant p1_101 Symptoms ['healthy'] => []
Participant 86 Symptoms ['healthy'] => []
Participant p1_14 Symptoms ['healthy'] => []
Participant p1_19 Symptoms ['cough'] => ['cough']
Participant p1_100 Symptoms ['healthy'] => []
Participant 108 Symptoms ['healthy'] => []
Participant p1_17 Symptoms ['healthy'] => []
Participant 6 Symptoms ['healthy'] => []
Participant 70 Symptoms ['healthy'] => []
Participant p1_509 Symptoms ['healthy'] => []
Participant 221 Symptoms ['healthy'] => []
Participant p1_508 Symptoms ['healthy'] => []
Participant p1_507 Symptoms ['healthy'] => []
Participant p1_145 Symptoms ['healthy'] => []
Participant 121 Symptoms ['healthy'] => []
Participant 18 Symptoms ['healthy'] => []
Participant 160 Symptoms ['healthy'] => []
Participant 143 Symptoms ['healthy'] => []
Participant p1_516 Symptoms ['healthy'] => []
Participant 99 Symptoms ['healthy'] => []
Participant p1_524 Symptoms ['healthy'] => []
Participant 131 Symptoms ['healthy'] => []
Participant p1_518 Symptoms ['healthy'] => []
Participant p1_510 Symptoms ['healthy'] => []
Participant p1_206 Symptoms ['healthy'] => []
Participant 155 Symptoms ['healthy'] => []
Participant 96 Symptoms ['healthy'] => []
Participant 211 Symptoms ['healthy'] => []
Participant 130 Symptoms ['healthy'] => []
Participant p1_515 Symptoms ['hand_muscles_pain'] => ['hand_muscles_pain']
Participant p1_514 Symptoms ['healthy'] => []
Participant 82 Symptoms ['healthy'] => []
Participant p1_521 Symptoms ['weakness'] => ['weakness']
Participant p1_522 Symptoms ['healthy'] => []
Participant p1_238 Symptoms ['healthy'] => []
Participant 26 Symptoms ['healthy'] => []
Participant p1_124 Symptoms ['healthy'] => []
Participant p1_550 Symptoms ['healthy'] => []
Participant p1_20 Symptoms ['cough'] => ['cough']
Participant 54 Symptoms ['healthy'] => []
Participant 71 Symptoms ['healthy'] => []
Participant p1_526 Symptoms ['healthy'] => []
Participant p1_16 Symptoms ['healthy'] => []
Participant 161 Symptoms ['healthy'] => []
Participant p1_525 Symptoms ['abdominal_pain'] => ['abdominal_pain']
Participant 194 Symptoms ['healthy'] => []
Participant p1_519 Symptoms ['healthy'] => []
Participant p1_534 Symptoms ['healthy'] => []
Participant p1_527 Symptoms ['healthy'] => []
Participant p1_157 Symptoms ['healthy'] => []
Participant p1_106 Symptoms ['healthy'] => []
Participant p1_530 Symptoms ['healthy'] => []
Participant 149 Symptoms ['healthy'] => []
Participant 67 Symptoms ['healthy'] => []
Participant p1_287 Symptoms ['healthy'] => []
Participant p1_131 Symptoms ['healthy'] => []
Participant 102 Symptoms ['healthy'] => []
Participant p1_414 Symptoms ['healthy'] => []
Participant p1_531 Symptoms ['healthy'] => []
Participant 170 Symptoms ['healthy'] => []
Participant p1_33 Symptoms ['cough'] => ['cough']
Participant p1_533 Symptoms ['healthy'] => []
Participant p1_532 Symptoms ['healthy'] => []
Participant p1_266 Symptoms ['healthy'] => []
Participant p1_536 Symptoms ['healthy'] => []
Participant p1_537 Symptoms ['healthy'] => []
Participant p1_535 Symptoms ['cold'] => ['cold']
Participant 120 Symptoms ['healthy'] => []
Participant 220 Symptoms ['healthy'] => []
Participant p1_154 Symptoms ['healthy'] => []
Participant 137 Symptoms ['healthy'] => []
Participant 40 Symptoms ['healthy'] => []
Participant p1_542 Symptoms ['healthy'] => []
Participant p1_538 Symptoms ['healthy'] => []
Participant p1_543 Symptoms ['healthy'] => []
Participant p1_554 Symptoms ['diarrhea', 'vomiting', 'cough', 'cold', 'other'] => ['diarrhea', 'vomiting', 'cough', 'cold', 'other']
Participant p1_119 Symptoms ['healthy'] => []
Participant p1_545 Symptoms ['cold'] => ['cold']
Participant 74 Symptoms ['healthy'] => []
Participant 248 Symptoms ['healthy'] => []
Participant p1_549 Symptoms ['healthy'] => []
Participant 4 Symptoms ['healthy'] => []
Participant p1_544 Symptoms ['healthy'] => []
Participant p1_412 Symptoms ['healthy'] => []
Participant p1_547 Symptoms ['healthy'] => []
Participant p1_551 Symptoms ['healthy'] => []
Participant 206 Symptoms ['dizziness'] => ['dizziness']
Participant 58 Symptoms ['healthy'] => []
Participant 191 Symptoms ['healthy'] => []
Participant 119 Symptoms ['healthy'] => []
Participant 261 Symptoms ['healthy'] => []
Participant p1_553 Symptoms ['cold'] => ['cold']
Participant 116 Symptoms ['healthy'] => []
Participant 93 Symptoms ['healthy'] => []
Participant p1_203 Symptoms ['healthy'] => []
Participant 16 Symptoms ['healthy'] => []
Participant 146 Symptoms ['weakness'] => ['weakness']
Participant 154 Symptoms ['healthy'] => []
Participant 122 Symptoms ['healthy'] => []
Participant p1_546 Symptoms ['weakness'] => ['weakness']
Participant 151 Symptoms ['healthy'] => []
Participant p1_558 Symptoms ['healthy'] => []
Participant p1_402 Symptoms ['healthy'] => []
Participant 78 Symptoms ['healthy'] => []
Participant p1_560 Symptoms ['healthy'] => []
Participant p1_559 Symptoms ['healthy'] => []
Participant 232 Symptoms ['healthy'] => []
Participant p1_557 Symptoms ['healthy'] => []
Participant p1_204 Symptoms ['healthy'] => []
Participant 85 Symptoms ['healthy'] => []
Participant p1_562 Symptoms ['healthy'] => []
Participant 186 Symptoms ['cold'] => ['cold']
Participant p1_565 Symptoms ['healthy'] => []

Participant p1_594 Symptoms ['healthy'] => []
Participant p1_592 Symptoms ['headache'] => ['headache']
Participant p1_582 Symptoms ['healthy'] => []
Participant 181 Symptoms ['healthy'] => []
Participant 162 Symptoms ['healthy'] => []
Participant p1_596 Symptoms ['cold'] => ['cold']
Participant p1_599 Symptoms ['healthy'] => []
Participant p1_595 Symptoms ['healthy'] => []
Participant 101 Symptoms ['healthy'] => []
Participant 212 Symptoms ['healthy'] => []
Participant p1_608 Symptoms ['abdominal_pain'] => ['abdominal_pain']
Participant 110 Symptoms ['healthy'] => []
Participant p1_254 Symptoms ['healthy'] => []
Participant 31 Symptoms ['healthy'] => []
Participant p1_609 Symptoms ['healthy'] => []
Participant 68 Symptoms ['cough', 'weakness'] => ['cough', 'weakness']
Participant p1_600 Symptoms ['healthy'] => []
Participant p1_604 Symptoms ['sore_throat'] => ['sore_throat']
Participant p1_601 Symptoms ['weakness'] => ['weakness']
Participant 36 Symptoms ['healthy'] => []
Participant p1_613 Symptoms ['healthy'] => []
Participant p1_606 Symptoms ['healthy'] => []
Participant p1_539 Symptoms ['cough'] => ['cough']
Participant p1_616 Symptoms ['headache'] => ['headache']
Participant p1_614 Symptoms ['muscles_pain'] => ['muscles_pain']
Participant 296 Symptoms ['healthy'] => []
Participant p1_615 Symptoms ['muscles_pain', 'other'] => ['muscles_pain', 'other']
Participant 182 Symptoms ['healthy'] => []
Participant p1_617 Symptoms ['healthy'] => []
Participant p1_620 Symptoms ['healthy'] => []
Participant p1_618 Symptoms ['healthy'] => []
Participant p1_223 Symptoms ['cold'] => ['cold']
Participant p1_621 Symptoms ['healthy'] => []
Participant p1_622 Symptoms ['healthy'] => []
Participant p1_634 Symptoms ['healthy'] => []
Participant p1_628 Symptoms ['healthy'] => []
Participant p1_625 Symptoms ['healthy'] => []
Participant p1_631 Symptoms ['healthy'] => []
Participant p1_626 Symptoms ['healthy'] => []
Participant p1_630 Symptoms ['healthy'] => []
Participant p1_637 Symptoms ['muscles_pain'] => ['muscles_pain']
Participant p1_627 Symptoms ['healthy'] => []
Participant p1_629 Symptoms ['healthy'] => []
Participant p1_276 Symptoms ['healthy'] => []
Participant p1_632 Symptoms ['healthy'] => []
Participant p1_635 Symptoms ['healthy'] => []
Participant 175 Symptoms ['healthy'] => []
Participant p1_636 Symptoms ['healthy'] => []
Participant 69 Symptoms ['healthy'] => []
Participant p1_638 Symptoms ['healthy'] => []
Participant p1_639 Symptoms ['healthy'] => []
Participant p1_640 Symptoms ['healthy'] => []
Participant 25 Symptoms ['healthy'] => []
Participant p1_641 Symptoms ['healthy'] => []
Participant 92 Symptoms ['weakness', 'chest_pain'] => ['weakness', 'chest_pain']
Participant 126 Symptoms ['healthy'] => []
Participant p1_298 Symptoms ['healthy'] => []
Participant p1_642 Symptoms ['healthy'] => []
Participant p1_650 Symptoms ['healthy'] => []
Participant 169 Symptoms ['healthy'] => []
Participant p1_649 Symptoms ['healthy'] => []
Participant p1_597 Symptoms ['healthy'] => []
Participant 309 Symptoms ['healthy'] => []
Participant p1_645 Symptoms ['healthy'] => []
Participant 230 Symptoms ['weakness', 'muscles_pain'] => ['weakness', 'muscles_pain']
Participant 275 Symptoms ['cough', 'muscles_pain'] => ['cough', 'muscles_pain']
Participant p1_647 Symptoms ['healthy'] => []
Participant p1_646 Symptoms ['healthy'] => []
Participant p1_591 Symptoms ['muscles_pain'] => ['muscles_pain']
Participant 165 Symptoms ['healthy'] => []
Participant 187 Symptoms ['cold'] => ['cold']
Participant p1_244 Symptoms ['healthy'] => []
Participant 365 Symptoms ['healthy'] => []
Participant 329 Symptoms ['healthy'] => []
Participant 247 Symptoms ['healthy'] => []
Participant 198 Symptoms ['healthy'] => []
Participant 323 Symptoms ['cough', 'dyspnea', 'weakness'] => ['cough', 'dyspnea', 'weakness']
Participant 603 Symptoms ['ear_pain'] => ['ear_pain']
Participant 1205 Symptoms ['healthy'] => []
Participant 595 Symptoms ['healthy'] => []
Participant 511 Symptoms ['healthy'] => []
Participant 1149 Symptoms ['healthy'] => []
Participant 1298 Symptoms ['muscles_pain'] => ['muscles_pain']
Participant 368 Symptoms ['cold', 'sore_throat'] => ['cold', 'sore_throat']
Participant 1286 Symptoms ['healthy'] => []
Participant 1129 Symptoms ['healthy'] => []
Participant 657 Symptoms ['healthy'] => []
Participant 624 Symptoms ['weakness'] => ['weakness']
Participant 37 Symptoms ['healthy'] => []
Participant 1266 Symptoms ['healthy'] => []
Participant 841 Symptoms ['weakness', 'muscles_pain'] => ['weakness', 'muscles_pain']
Participant 1462 Symptoms ['healthy'] => []
Participant 830 Symptoms ['healthy'] => []
Participant 1184 Symptoms ['healthy'] => []
Participant 526 Symptoms ['healthy'] => []
Participant 759 Symptoms ['healthy'] => []
Participant 731 Symptoms ['healthy'] => []
Participant 904 Symptoms ['healthy'] => []
Participant 1124 Symptoms ['healthy'] => []
Participant 3 Symptoms ['healthy'] => []
Participant 1757 Symptoms ['healthy'] => []
Participant 549 Symptoms ['healthy'] => []
Participant 328 Symptoms ['healthy'] => []
Participant 864 Symptoms ['healthy'] => []
Participant 1120 Symptoms ['healthy'] => []
Participant 2015 Symptoms ['diarrhea'] => ['diarrhea']
Participant 1307 Symptoms ['healthy'] => []
Participant 83 Symptoms ['healthy'] => []
Participant 338 Symptoms ['healthy'] => []
Participant 716 Symptoms ['healthy'] => []
Participant 705 Symptoms ['healthy'] => []
Participant 704 Symptoms ['healthy'] => []
Participant 542 Symptoms ['healthy'] => []
Participant 1165 Symptoms ['healthy'] => []
Participant 1231 Symptoms ['healthy'] => []
Participant 292 Symptoms ['healthy'] => []
Participant 4016 Symptoms ['healthy'] => []
Participant 805 Symptoms ['healthy'] => []
Participant 604 Symptoms ['diarrhea'] => ['diarrhea']
Participant 646 Symptoms ['weakness'] => ['weakness']
Participant 41 Symptoms ['healthy'] => []
Participant 594 Symptoms ['healthy'] => []
Participant 495 Symptoms ['healthy'] => []
Participant 762 Symptoms ['healthy'] => []
Participant 284 Symptoms ['healthy'] => []
Participant 1302 Symptoms ['healthy'] => []
Participant 487 Symptoms ['healthy'] => []
Participant 1285 Symptoms ['healthy'] => []
Participant 623 Symptoms ['healthy'] => []
Participant 504 Symptoms ['healthy'] => []
Participant 451 Symptoms ['cough', 'cold', 'sore_throat'] => ['cough', 'cold', 'sore_throat']
Participant 133 Symptoms ['healthy'] => []
Participant 856 Symptoms ['healthy'] => []
Participant 164 Symptoms ['healthy'] => []
Participant 366 Symptoms ['healthy'] => []
Participant 642 Symptoms ['healthy'] => []
Participant 197 Symptoms ['healthy'] => []
Participant 580 Symptoms ['healthy'] => []
Participant 1498 Symptoms ['healthy'] => []
Participant 4310 Symptoms ['healthy'] => []
Participant 1174 Symptoms ['healthy'] => []
Participant 413 Symptoms ['healthy'] => []
Participant 665 Symptoms ['healthy'] => []
Participant 4014 Symptoms ['healthy'] => []
Participant 1203 Symptoms ['healthy'] => []
Participant 2217 Symptoms ['healthy'] => []
Participant 621 Symptoms ['healthy'] => []
Participant 1198 Symptoms ['healthy'] => []
Participant 551 Symptoms ['healthy'] => []
Participant 1831 Symptoms ['healthy'] => []
Participant 1814 Symptoms ['healthy'] => []
Participant 418 Symptoms ['healthy'] => []
Participant 764 Symptoms ['cough'] => ['cough']
Participant 415 Symptoms ['healthy'] => []
Participant 1246 Symptoms ['healthy'] => []
Participant 1235 Symptoms ['healthy'] => []
Participant 750 Symptoms ['headache', 'other'] => ['headache', 'other']
Participant 729 Symptoms ['healthy'] => []
Participant 1823 Symptoms ['healthy'] => []
Participant 1171 Symptoms ['healthy'] => []
Participant 615 Symptoms ['headache'] => ['headache']
Participant 143 Symptoms ['healthy'] => []
Participant 318 Symptoms ['cold'] => ['cold']
Participant 819 Symptoms ['healthy'] => []
Participant 571 Symptoms ['healthy'] => []
Participant 1789 Symptoms ['healthy'] => []
Participant 2121 Symptoms ['healthy'] => []
Participant 1243 Symptoms ['healthy'] => []
Participant 104 Symptoms ['cold', 'weakness'] => ['cold', 'weakness']
Participant 645 Symptoms ['healthy'] => []
Participant 1367 Symptoms ['headache'] => ['headache']
Participant 1237 Symptoms ['healthy'] => []
Participant 749 Symptoms ['healthy'] => []
Participant 80 Symptoms ['healthy'] => []
Participant 515 Symptoms ['headache', 'weakness', 'muscles_pain', 'other'] => ['headache', 'weakness', 'muscles_pain', 'other']
Participant 1169 Symptoms ['weakness'] => ['weakness']
Participant 1558 Symptoms ['healthy'] => []
Participant 681 Symptoms ['healthy'] => []
Participant 747 Symptoms ['healthy'] => []
Participant 76 Symptoms ['healthy'] => []
Participant 1400 Symptoms ['healthy'] => []
Participant 1281 Symptoms ['healthy'] => []
Participant 748 Symptoms ['healthy'] => []
Participant 574 Symptoms ['healthy'] => []
Participant 736 Symptoms ['healthy'] => []
Participant 662 Symptoms ['weakness'] => ['weakness']
Participant 448 Symptoms ['cold', 'weakness'] => ['cold', 'weakness']
Participant 1656 Symptoms ['healthy'] => []
Participant 564 Symptoms ['healthy'] => []
Participant 497 Symptoms ['healthy'] => []
Participant 1771 Symptoms ['healthy'] => []
Participant 441 Symptoms ['healthy'] => []
Participant 1271 Symptoms ['healthy'] => []
Participant 276 Symptoms ['healthy'] => []
Participant 891 Symptoms ['healthy'] => []
Participant 1505 Symptoms ['healthy'] => []
Participant 6 Symptoms ['healthy'] => []
Participant 689 Symptoms ['healthy'] => []
Participant 1233 Symptoms ['weakness'] => ['weakness']
Participant 295 Symptoms ['healthy'] => []
Participant 457 Symptoms ['healthy'] => []
Participant 1621 Symptoms ['healthy'] => []
Participant 1445 Symptoms ['cough'] => ['cough']
Participant 742 Symptoms ['healthy'] => []
Participant 1276 Symptoms ['healthy'] => []
Participant 1207 Symptoms ['healthy'] => []
Participant 1222 Symptoms ['healthy'] => []
Participant 1591 Symptoms ['healthy'] => []
Participant 1149 Symptoms ['healthy'] => []
Participant 136 Symptoms ['healthy'] => []
Participant 2127 Symptoms ['healthy'] => []
Participant 1125 Symptoms ['dyspnea'] => ['dyspnea']
Participant 1800 Symptoms ['healthy'] => []
Participant 337 Symptoms ['healthy'] => []
Participant 364 Symptoms ['healthy'] => []
Participant 1179 Symptoms ['healthy'] => []
Participant 1931 Symptoms ['healthy'] => []
Participant 2111 Symptoms ['healthy'] => []
Participant 550 Symptoms ['healthy'] => []
Participant 499 Symptoms ['healthy'] => []
Participant 1132 Symptoms ['healthy'] => []
Participant 1148 Symptoms ['healthy'] => []
Participant 59 Symptoms ['healthy'] => []
Participant 4329 Symptoms ['healthy'] => []
Participant 109 Symptoms ['healthy'] => []
Participant 1111 Symptoms ['healthy'] => []
Participant 1274 Symptoms ['healthy'] => []
Participant 449 Symptoms ['healthy'] => []
Participant 1289 Symptoms ['healthy'] => []
Participant 206 Symptoms ['back_or_neck_pain', 'other'] => ['back_or_neck_pain', 'other']
Participant 1109 Symptoms ['healthy'] => []
Participant 1501 Symptoms ['healthy'] => []
Participant 475 Symptoms ['healthy'] => []
Participant 384 Symptoms ['healthy'] => []
Participant 596 Symptoms ['healthy'] => []
Participant 205 Symptoms ['healthy'] => []
Participant 730 Symptoms ['healthy'] => []
Participant 1564 Symptoms ['healthy'] => []
Participant 851 Symptoms ['healthy'] => []
Participant 2002 Symptoms ['healthy'] => []
Participant 48 Symptoms ['weakness', 'muscles_pain'] => ['weakness', 'muscles_pain']
Participant 1320 Symptoms ['healthy'] => []
Participant 2413 Symptoms ['healthy'] => []
Participant 1245 Symptoms ['healthy'] => []
Participant 1896 Symptoms ['healthy'] => []
Participant 1539 Symptoms ['healthy'] => []
Participant 421 Symptoms ['healthy'] => []
Participant 1180 Symptoms ['healthy'] => []
Participant 1182 Symptoms ['healthy'] => []
Participant 527 Symptoms ['healthy'] => []
Participant 446 Symptoms ['healthy'] => []
Participant 1199 Symptoms ['healthy'] => []
Participant 4425 Symptoms ['muscles_pain'] => ['muscles_pain']
Participant 896 Symptoms ['abdominal_pain'] => ['abdominal_pain']
Participant 325 Symptoms ['healthy'] => []
Participant 577 Symptoms ['healthy'] => []
Participant 531 Symptoms ['healthy'] => []
Participant 1131 Symptoms ['muscles_pain'] => ['muscles_pain']
Participant 251 Symptoms ['healthy'] => []
Participant 2175 Symptoms ['healthy'] => []
Participant 1844 Symptoms ['healthy'] => []
Participant 370 Symptoms ['healthy'] => []
Participant 20 Symptoms ['healthy'] => []
Participant 4530 Symptoms ['healthy'] => []
Participant 73 Symptoms ['sore_throat'] => ['sore_throat']
Participant 587 Symptoms ['healthy'] => []
Participant 129 Symptoms ['healthy'] => []
Participant 588 Symptoms ['headache', 'vomiting'] => ['headache', 'vomiting']
Participant 291 Symptoms ['healthy'] => []
Participant 894 Symptoms ['healthy'] => []
Participant 1871 Symptoms ['healthy'] => []
Participant 1332 Symptoms ['healthy'] => []
Participant 1339 Symptoms ['other'] => ['other']
Participant 732 Symptoms ['headache'] => ['headache']
Participant 252 Symptoms ['healthy'] => []
Participant 230 Symptoms ['healthy'] => []
Participant 1143 Symptoms ['healthy'] => []
Participant 766 Symptoms ['healthy'] => []
Participant 279 Symptoms ['healthy'] => []
Participant 1206 Symptoms ['diarrhea'] => ['diarrhea']
Participant 518 Symptoms ['healthy'] => []
Participant 1818 Symptoms ['healthy'] => []
Participant 437 Symptoms ['healthy'] => []
Participant 443 Symptoms ['healthy'] => []
Participant 1298 Symptoms ['headache', 'weakness', 'muscles_pain', 'other'] => ['headache', 'weakness', 'muscles_pain', 'other']
Participant 1323 Symptoms ['healthy'] => []
Participant 27 Symptoms ['healthy'] => []
Participant 1110 Symptoms ['healthy'] => []
Participant 465 Symptoms ['healthy'] => []
Participant 1859 Symptoms ['healthy'] => []
Participant 72 Symptoms ['healthy'] => []
Participant 1181 Symptoms ['leg_pain', 'muscles_pain'] => ['leg_pain', 'muscles_pain']
Participant 833 Symptoms ['healthy'] => []
Participant 385 Symptoms ['healthy'] => []
Participant 1216 Symptoms ['healthy'] => []
Participant 1861 Symptoms ['weakness'] => ['weakness']
Participant 740 Symptoms ['healthy'] => []
Participant 559 Symptoms ['healthy'] => []
Participant 2412 Symptoms ['healthy'] => []
Participant 1122 Symptoms ['cough', 'cold'] => ['cough', 'cold']
Participant 391 Symptoms ['cough'] => ['cough']
Participant 103 Symptoms ['healthy'] => []
Participant 4401 Symptoms ['healthy'] => []
Participant 863 Symptoms ['healthy'] => []
Participant 18 Symptoms ['healthy'] => []
Participant 168 Symptoms ['healthy'] => []
Participant 824 Symptoms ['healthy'] => []
Participant 102 Symptoms ['healthy'] => []
Participant 1542 Symptoms ['healthy'] => []
Participant 301 Symptoms ['healthy'] => []
Participant 501 Symptoms ['healthy'] => []
Participant 2155 Symptoms ['healthy'] => []
Participant 4500 Symptoms ['healthy'] => []
Participant 1573 Symptoms ['healthy'] => []
Participant 546 Symptoms ['healthy'] => []
Participant 204 Symptoms ['healthy'] => []
Participant 2156 Symptoms ['healthy'] => []
Participant 1511 Symptoms ['cough'] => ['cough']
Participant 868 Symptoms ['sore_throat', 'headache', 'cold', 'weakness', 'muscles_pain'] => ['sore_throat', 'headache', 'cold', 'weakness', 'muscles_pain']
Participant 889 Symptoms ['healthy'] => []
Participant 713 Symptoms ['healthy'] => []
Participant 120 Symptoms ['healthy'] => []
Participant 814 Symptoms ['healthy'] => []
Participant 1195 Symptoms ['healthy'] => []
Participant 743 Symptoms ['healthy'] => []
Participant 717 Symptoms ['healthy'] => []
Participant 234 Symptoms ['healthy'] => []
Participant 266 Symptoms ['healthy'] => []
Participant 412 Symptoms ['muscles_pain'] => ['muscles_pain']
Participant 651 Symptoms ['headache', 'muscles_pain'] => ['headache', 'muscles_pain']
Participant 194 Symptoms ['healthy'] => []
Participant 753 Symptoms ['healthy'] => []
Participant 1146 Symptoms ['healthy'] => []
Participant 200 Symptoms ['healthy'] => []
Participant 1840 Symptoms ['healthy'] => []
Participant 1 Symptoms ['healthy'] => []
Participant 2443 Symptoms ['healthy'] => []
Participant 281 Symptoms ['healthy'] => []
Participant 1116 Symptoms ['healthy'] => []
Participant 1805 Symptoms ['healthy'] => []
Participant 1155 Symptoms ['healthy'] => []
Participant 1523 Symptoms ['cold', 'other'] => ['cold', 'other']
Participant 2014 Symptoms ['healthy'] => []
Participant 2469 Symptoms ['healthy'] => []
Participant 466 Symptoms ['healthy'] => []
Participant 572 Symptoms ['healthy'] => []
Participant 727 Symptoms ['healthy'] => []
Participant 653 Symptoms ['healthy'] => []
Participant 53 Symptoms ['healthy'] => []
Participant 1123 Symptoms ['healthy'] => []
Participant 1118 Symptoms ['healthy'] => []
Participant 1474 Symptoms ['healthy'] => []
Participant 1448 Symptoms ['healthy'] => []
Participant 484 Symptoms ['healthy'] => []
Participant 573 Symptoms ['healthy'] => []
Participant 880 Symptoms ['healthy'] => []
Participant 517 Symptoms ['weakness'] => ['weakness']
Participant 670 Symptoms ['healthy'] => []
Participant 319 Symptoms ['healthy'] => []
Participant 648 Symptoms ['healthy'] => []
Participant 24 Symptoms ['healthy'] => []
Participant 1507 Symptoms ['healthy'] => []
Participant 528 Symptoms ['healthy'] => []
Participant 1223 Symptoms ['healthy'] => []
Participant 846 Symptoms ['healthy'] => []
Participant 489 Symptoms ['healthy'] => []
Participant 511 Symptoms ['healthy'] => []
Participant 1259 Symptoms ['healthy'] => []
Participant 706 Symptoms ['healthy'] => []
Participant 810 Symptoms ['healthy'] => []
Participant 4515 Symptoms ['weakness'] => ['weakness']
Participant 582 Symptoms ['healthy'] => []
Participant 233 Symptoms ['healthy'] => []
Participant 1278 Symptoms ['weakness', 'dyspnea'] => ['weakness', 'dyspnea']
Participant 382 Symptoms ['healthy'] => []
Participant 310 Symptoms ['healthy'] => []
Participant 4319 Symptoms ['healthy'] => []
Participant 900 Symptoms ['healthy'] => []
Participant 803 Symptoms ['weakness'] => ['weakness']
Participant 1565 Symptoms ['healthy'] => []
Participant 112 Symptoms ['healthy'] => []
Participant 322 Symptoms ['healthy'] => []
Participant 472 Symptoms ['healthy'] => []
Participant 1597 Symptoms ['healthy'] => []
Participant 576 Symptoms ['muscles_pain'] => ['muscles_pain']
Participant 525 Symptoms ['healthy'] => []
Participant 1585 Symptoms ['healthy'] => []
Participant 1218 Symptoms ['healthy'] => []
Participant 4898 Symptoms ['healthy'] => []
Participant 616 Symptoms ['healthy'] => []
Participant 637 Symptoms ['cold', 'leg_pain'] => ['cold', 'leg_pain']
Participant 1201 Symptoms ['healthy'] => []
Participant 265 Symptoms ['healthy'] => []
Participant 47 Symptoms ['healthy'] => []
Participant 377 Symptoms ['healthy'] => []
Participant 1406 Symptoms ['healthy'] => []
Participant 108 Symptoms ['healthy'] => []
Participant 1543 Symptoms ['healthy'] => []
Participant 700 Symptoms ['healthy'] => []
Participant 2209 Symptoms ['cough'] => ['cough']
Participant 407 Symptoms ['healthy'] => []
Participant 211 Symptoms ['healthy'] => []
Participant 1429 Symptoms ['healthy'] => []
Participant 683 Symptoms ['weakness'] => ['weakness']
Participant 1144 Symptoms ['healthy'] => []
Participant 702 Symptoms ['healthy'] => []
Participant 1547 Symptoms ['healthy'] => []
Participant 1280 Symptoms ['healthy'] => []
Participant 1517 Symptoms ['healthy'] => []
Participant 2090 Symptoms ['healthy'] => []
Participant 1141 Symptoms ['healthy'] => []
Participant 21 Symptoms ['healthy'] => []
Participant 1299 Symptoms ['healthy'] => []
Participant 313 Symptoms ['healthy'] => []
Participant 1227 Symptoms ['healthy'] => []
Participant 4104 Symptoms ['healthy'] => []
Participant 132 Symptoms ['healthy'] => []
Participant 768 Symptoms ['healthy'] => []
Participant 1716 Symptoms ['healthy'] => []
Participant 4411 Symptoms ['cold'] => ['cold']
Participant 2562 Symptoms ['healthy'] => []
Participant 2039 Symptoms ['healthy'] => []

Participant 2452 Symptoms ['healthy'] => []
Participant 1884 Symptoms ['healthy'] => []
Participant 1192 Symptoms ['healthy'] => []
Participant 502 Symptoms ['healthy'] => []
Participant 1113 Symptoms ['healthy'] => []
Participant 1629 Symptoms ['healthy'] => []
Participant 2409 Symptoms ['healthy'] => []
Participant 733 Symptoms ['healthy'] => []
Participant 1315 Symptoms ['healthy'] => []
Participant 1736 Symptoms ['healthy'] => []
Participant 693 Symptoms ['healthy'] => []
Participant 770 Symptoms ['abdominal_pain', 'weakness'] => ['abdominal_pain', 'weakness']
Participant 1324 Symptoms ['healthy'] => []
Participant 769 Symptoms ['healthy'] => []
Participant 2308 Symptoms ['healthy'] => []
Participant 1548 Symptoms ['healthy'] => []
Participant 297 Symptoms ['healthy'] => []
Participant 1145 Symptoms ['cold'] => ['cold']
Participant 2104 Symptoms ['healthy'] => []
Participant 862 Symptoms ['healthy'] => []
Participant 2168 Symptoms ['healthy'] => []
Participant 1114 Symptoms ['healthy'] => []
Participant 447 Symptoms ['healthy'] => []
Participant 725 Symptoms ['healthy'] => []
Participant 2069 Symptoms ['healthy'] => []
Participant 688 Symptoms ['healthy'] => []
Participant 121 Symptoms ['healthy'] => []
Participant 554 Symptoms ['headache'] => ['headache']
Participant 1255 Symptoms ['healthy'] => []
Participant 450 Symptoms ['healthy'] => []
Participant 1331 Symptoms ['healthy'] => []
Participant 1869 Symptoms ['healthy'] => []
Participant 308 Symptoms ['healthy'] => []
Participant 1373 Symptoms ['healthy'] => []
Participant 4313 Symptoms ['healthy'] => []
Participant 1258 Symptoms ['healthy'] => []
Participant 2401 Symptoms ['healthy'] => []
Participant 4202 Symptoms ['healthy'] => []
Participant 1252 Symptoms ['healthy'] => []
Participant 1572 Symptoms ['healthy'] => []
Participant 519 Symptoms ['healthy'] => []
Participant 490 Symptoms ['healthy'] => []
Participant 4508 Symptoms ['healthy'] => []
Participant 2094 Symptoms ['healthy'] => []
Participant 598 Symptoms ['healthy'] => []
Participant 866 Symptoms ['chills', 'weakness', 'muscles_pain', 'headache'] => ['chills', 'weakness', 'muscles_pain', 'headache']
Participant 277 Symptoms ['healthy'] => []
Participant 575 Symptoms ['healthy'] => []
Participant 1232 Symptoms ['healthy'] => []
Participant 1522 Symptoms ['healthy'] => []
Participant 2008 Symptoms ['weakness'] => ['weakness']
Participant 440 Symptoms ['healthy'] => []
Participant 23 Symptoms ['healthy'] => []
Participant 1424 Symptoms ['healthy'] => []
Participant 860 Symptoms ['healthy'] => []
Participant 757 Symptoms ['healthy'] => []
Participant 1727 Symptoms ['healthy'] => []
Participant 402 Symptoms ['healthy'] => []
Participant 811 Symptoms ['healthy'] => []
Participant 595 Symptoms ['healthy'] => []
Participant 1161 Symptoms ['weakness'] => ['weakness']
Participant 1763 Symptoms ['healthy'] => []
Participant 2166 Symptoms ['healthy'] => []
Participant 1330 Symptoms ['healthy'] => []
Participant 74 Symptoms ['healthy'] => []
Participant 1446 Symptoms ['healthy'] => []
Participant 283 Symptoms ['healthy'] => []
Participant 652 Symptoms ['healthy'] => []
Participant 2548 Symptoms ['healthy'] => []
Participant 1238 Symptoms ['healthy'] => []
Participant 712 Symptoms ['healthy'] => []
Participant 865 Symptoms ['healthy'] => []
Participant 155 Symptoms ['healthy'] => []
Participant 2583 Symptoms ['healthy'] => []
Participant 161 Symptoms ['healthy'] => []
Participant 93 Symptoms ['healthy'] => []
Participant 892 Symptoms ['healthy'] => []
Participant 1882 Symptoms ['healthy'] => []
Participant 1314 Symptoms ['healthy'] => []
Participant 2179 Symptoms ['healthy'] => []
Participant 485 Symptoms ['weakness', 'muscles_pain'] => ['weakness', 'muscles_pain']
Participant 116 Symptoms ['healthy'] => []
Participant 1439 Symptoms ['healthy'] => []
Participant 1762 Symptoms ['healthy'] => []
Participant 1760 Symptoms ['healthy'] => []
Participant 1327 Symptoms ['healthy'] => []
Participant 1150 Symptoms ['healthy'] => []
Participant 191 Symptoms ['healthy'] => []
Participant 585 Symptoms ['healthy'] => []
Participant 468 Symptoms ['healthy'] => []
Participant 899 Symptoms ['healthy'] => []
Participant 4422 Symptoms ['healthy'] => []
Participant 1200 Symptoms ['healthy'] => []
Participant 625 Symptoms ['healthy'] => []
Participant 606 Symptoms ['healthy'] => []
Participant 754 Symptoms ['cold'] => ['cold']
Participant 1782 Symptoms ['healthy'] => []
Participant 674 Symptoms ['healthy'] => []
Participant 679 Symptoms ['healthy'] => []
Participant 503 Symptoms ['healthy'] => []
Participant 1220 Symptoms ['healthy'] => []
Participant 156 Symptoms ['healthy'] => []
Participant 760 Symptoms ['healthy'] => []
Participant 1175 Symptoms ['healthy'] => []
Participant 460 Symptoms ['healthy'] => []
Participant 1241 Symptoms ['healthy'] => []
Participant 1270 Symptoms ['healthy'] => []
Participant 114 Symptoms ['healthy'] => []
Participant 758 Symptoms ['healthy'] => []
Participant 2567 Symptoms ['healthy'] => []
Participant 739 Symptoms ['healthy'] => []
Participant 506 Symptoms ['healthy'] => []
Participant 859 Symptoms ['healthy'] => []
Participant 1521 Symptoms ['healthy'] => []
Participant 43 Symptoms ['other'] => ['other']
Participant 2569 Symptoms ['healthy'] => []
Participant 808 Symptoms ['cough'] => ['cough']
Participant 1300 Symptoms ['healthy'] => []
Participant 1263 Symptoms ['healthy'] => []
Participant 694 Symptoms ['healthy'] => []
Participant 1173 Symptoms ['healthy'] => []
Participant 458 Symptoms ['healthy'] => []
Participant 2183 Symptoms ['healthy'] => []
Participant 4 Symptoms ['healthy'] => []
Participant 1221 Symptoms ['healthy'] => []
Participant 1239 Symptoms ['healthy'] => []
Participant 535 Symptoms ['healthy'] => []
Participant 1589 Symptoms ['healthy'] => []
Participant 1112 Symptoms ['healthy'] => []
Participant 1877 Symptoms ['healthy'] => []
Participant 2032 Symptoms ['healthy'] => []
Participant 210 Symptoms ['healthy'] => []
Participant 1228 Symptoms ['healthy'] => []
Participant 855 Symptoms ['diarrhea'] => ['diarrhea']
Participant 2213 Symptoms ['healthy'] => []
Participant 1718 Symptoms ['healthy'] => []
Participant 708 Symptoms ['healthy'] => []
Participant 1806 Symptoms ['healthy'] => []
Participant 477 Symptoms ['healthy'] => []
Participant 1183 Symptoms ['healthy'] => []
Participant 1742 Symptoms ['healthy'] => []
Participant 1204 Symptoms ['healthy'] => []
Participant 1748 Symptoms ['healthy'] => []
Participant 1761 Symptoms ['healthy'] => []
Participant 579 Symptoms ['healthy'] => []
Participant 1191 Symptoms ['healthy'] => []
Participant 296 Symptoms ['healthy'] => []
Participant 569 Symptoms ['healthy'] => []
Participant 134 Symptoms ['healthy'] => []
Participant 2227 Symptoms ['cold', 'weakness', 'feel_heat'] => ['cold', 'weakness', 'feel_heat']
Participant 1463 Symptoms ['healthy'] => []
Participant 2504 Symptoms ['healthy'] => []
Participant 1428 Symptoms ['healthy'] => []
Participant 2439 Symptoms ['healthy'] => []
Participant 1786 Symptoms ['healthy'] => []
Participant 4403 Symptoms ['healthy'] => []
Participant 478 Symptoms ['healthy'] => []
Participant 839 Symptoms ['healthy'] => []
Participant 812 Symptoms ['healthy'] => []
Participant 2607 Symptoms ['healthy'] => []
Participant 1157 Symptoms ['healthy'] => []
Participant 505 Symptoms ['healthy'] => []
Participant 50 Symptoms ['headache', 'sore_throat', 'vomiting', 'chills', 'weakness', 'muscles_pain', 'feel_heat'] => ['headache', 'sore_throat', 'vomiting', 'chills', 'weakness', 'muscles_pain', 'feel_heat']
Participant 287 Symptoms ['healthy'] => []
Participant 339 Symptoms ['healthy'] => []
Participant 715 Symptoms ['healthy'] => []
Participant 2211 Symptoms ['healthy'] => []
Participant 695 Symptoms ['healthy'] => []
Participant 543 Symptoms ['healthy'] => []
Participant 274 Symptoms ['healthy'] => []
Participant 122 Symptoms ['healthy'] => []
Participant 1273 Symptoms ['healthy'] => []
Participant 453 Symptoms ['healthy'] => []
Participant 1875 Symptoms ['healthy'] => []
Participant 1420 Symptoms ['healthy'] => []
Participant 829 Symptoms ['healthy'] => []
Participant 419 Symptoms ['healthy'] => []
Participant 718 Symptoms ['healthy'] => []
Participant 2509 Symptoms ['healthy'] => []
Participant 1117 Symptoms ['healthy'] => []
Participant 16 Symptoms ['healthy'] => []
Participant 2526 Symptoms ['healthy'] => []
Participant 607 Symptoms ['healthy'] => []
Participant 70 Symptoms ['healthy'] => []
Participant 28 Symptoms ['dizziness'] => ['dizziness']
Participant 4501 Symptoms ['healthy'] => []
Participant 433 Symptoms ['healthy'] => []
Participant 1178 Symptoms ['healthy'] => []
Participant 1205 Symptoms ['healthy'] => []
Participant 26 Symptoms ['healthy'] => []
Participant 428 Symptoms ['healthy'] => []
Participant 1726 Symptoms ['healthy'] => []
Participant 54 Symptoms ['cold'] => ['cold']
Participant 2120 Symptoms ['healthy'] => []
Participant 2148 Symptoms ['healthy'] => []
Participant 1856 Symptoms ['healthy'] => []
Participant 720 Symptoms ['healthy'] => []
Participant 4526 Symptoms ['healthy'] => []
Participant 1783 Symptoms ['healthy'] => []
Participant 2421 Symptoms ['healthy'] => []
Participant 2245 Symptoms ['healthy'] => []
Participant 19 Symptoms ['healthy'] => []
Participant 1147 Symptoms ['healthy'] => []
Participant 599 Symptoms ['healthy'] => []
Participant 570 Symptoms ['healthy'] => []
Participant 590 Symptoms ['healthy'] => []
Participant 1419 Symptoms ['healthy'] => []
Participant 2466 Symptoms ['weakness', 'headache', 'cough', 'cold', 'dyspnea', 'muscles_pain'] => ['weakness', 'headache', 'cough', 'cold', 'dyspnea', 'muscles_pain']
Participant 335 Symptoms ['healthy'] => []
Participant 1820 Symptoms ['healthy'] => []
Participant 533 Symptoms ['healthy'] => []
Participant 530 Symptoms ['healthy'] => []
Participant 40 Symptoms ['healthy'] => []
Participant 124 Symptoms ['healthy'] => []
Participant 1167 Symptoms ['healthy'] => []
Participant 4506 Symptoms ['cold'] => ['cold']
Participant 1607 Symptoms ['healthy'] => []
Participant 524 Symptoms ['healthy'] => []
Participant 192 Symptoms ['healthy'] => []
Participant 2107 Symptoms ['healthy'] => []
Participant 1250 Symptoms ['healthy'] => []
Participant 1644 Symptoms ['healthy'] => []
Participant 566 Symptoms ['healthy'] => []
Participant 4317 Symptoms ['healthy'] => []
Participant 464 Symptoms ['healthy'] => []
Participant 1784 Symptoms ['healthy'] => []
Participant 1476 Symptoms ['healthy'] => []
Participant 2084 Symptoms ['healthy'] => []
Participant 1583 Symptoms ['healthy'] => []
Participant 46 Symptoms ['healthy'] => []
Participant 1866 Symptoms ['healthy'] => []
Participant 2100 Symptoms ['healthy'] => []
Participant 800 Symptoms ['dyspnea'] => ['dyspnea']
Participant 1455 Symptoms ['healthy'] => []
Participant 2177 Symptoms ['healthy'] => []
Participant 1640 Symptoms ['healthy'] => []
Participant 1102 Symptoms ['healthy'] => []
Participant 643 Symptoms ['healthy'] => []
Participant 1518 Symptoms ['healthy'] => []
Participant 1747 Symptoms ['headache'] => ['headache']
Participant 1257 Symptoms ['healthy'] => []
Participant 1318 Symptoms ['healthy'] => []
Participant 1417 Symptoms ['healthy'] => []
Participant 1701 Symptoms ['healthy'] => []
Participant 1440 Symptoms ['healthy'] => []
Participant 1592 Symptoms ['sore_throat'] => ['sore_throat']
Participant 822 Symptoms ['healthy'] => []
Participant 1397 Symptoms ['healthy'] => []
Participant 877 Symptoms ['healthy'] => []
Participant 2609 Symptoms ['healthy'] => []
Participant 85 Symptoms ['cough', 'weakness'] => ['cough', 'weakness']
Participant 1381 Symptoms ['healthy'] => []
Participant 1325 Symptoms ['healthy'] => []
Participant 1322 Symptoms ['cold'] => ['cold']
Participant 1158 Symptoms ['healthy'] => []
Participant 1128 Symptoms ['healthy'] => []
Participant 1343 Symptoms ['healthy'] => []
Participant 149 Symptoms ['healthy'] => []
Participant 298 Symptoms ['weakness'] => ['weakness']
Participant 461 Symptoms ['healthy'] => []
Participant 563 Symptoms ['healthy'] => []
Participant 1876 Symptoms ['healthy'] => []
Participant 455 Symptoms ['healthy'] => []
Participant 1244 Symptoms ['healthy'] => []
Participant 2461 Symptoms ['healthy'] => []
Participant 1825 Symptoms ['healthy'] => []
Participant 644 Symptoms ['healthy'] => []
Participant 1321 Symptoms ['healthy'] => []
Participant 183 Symptoms ['sore_throat'] => ['sore_throat']
Participant 288 Symptoms ['healthy'] => []
Participant 2194 Symptoms ['healthy'] => []
Participant 1529 Symptoms ['healthy'] => []
Participant 4205 Symptoms ['healthy'] => []
Participant 2543 Symptoms ['healthy'] => []
Participant 272 Symptoms ['healthy'] => []
Participant 4523 Symptoms ['healthy'] => []
Participant 305 Symptoms ['healthy'] => []
Participant 343 Symptoms ['healthy'] => []
Participant 1472 Symptoms ['healthy'] => []
Participant 170 Symptoms ['healthy'] => []
Participant 1251 Symptoms ['healthy'] => []
Participant 96 Symptoms ['healthy'] => []
Participant 99 Symptoms ['healthy'] => []
Participant 2023 Symptoms ['healthy'] => []
Participant 2021 Symptoms ['healthy'] => []
Participant 2560 Symptoms ['healthy'] => []
Participant 827 Symptoms ['healthy'] => []
Participant 1832 Symptoms ['healthy'] => []
Participant 2585 Symptoms ['healthy'] => []
Participant 2800 Symptoms ['healthy'] => []
Participant 2540 Symptoms ['healthy'] => []
Participant 1655 Symptoms ['diarrhea'] => ['diarrhea']
Participant 1154 Symptoms ['healthy'] => []
Participant 470 Symptoms ['healthy'] => []
Participant 2445 Symptoms ['healthy'] => []
Participant 236 Symptoms ['healthy'] => []
Participant 1873 Symptoms ['healthy'] => []
Participant 2483 Symptoms ['cold'] => ['cold']
Participant 151 Symptoms ['healthy'] => []
Participant 238 Symptoms ['healthy'] => []
Participant 832 Symptoms ['healthy'] => []
Participant 2643 Symptoms ['cold', 'sore_throat'] => ['cold', 'sore_throat']
Participant 1898 Symptoms ['healthy'] => []
Participant 1567 Symptoms ['healthy'] => []
Participant 1850 Symptoms ['healthy'] => []
Participant 2099 Symptoms ['healthy'] => []
Participant 586 Symptoms ['healthy'] => []
Participant 1172 Symptoms ['weakness'] => ['weakness']
Participant 160 Symptoms ['healthy'] => []
Participant 555 Symptoms ['healthy'] => []
Participant 1886 Symptoms ['dyspnea'] => ['dyspnea']
Participant 1549 Symptoms ['healthy'] => []
Participant 1458 Symptoms ['healthy'] => []
Participant 1587 Symptoms ['healthy'] => []
Participant 2216 Symptoms ['healthy'] => []
Participant 2495 Symptoms ['healthy'] => []
Participant 1804 Symptoms ['healthy'] => []
Participant 2079 Symptoms ['cough', 'sore_throat'] => ['cough', 'sore_throat']
Participant 2432 Symptoms ['healthy'] => []
Participant 2152 Symptoms ['healthy'] => []
Participant 1893 Symptoms ['healthy'] => []
Participant 56 Symptoms ['healthy'] => []
Participant 2252 Symptoms ['healthy'] => []
Participant 144 Symptoms ['healthy'] => []
Participant 344 Symptoms ['healthy'] => []
Participant 34 Symptoms ['healthy'] => []
Participant 2822 Symptoms ['healthy'] => []
Participant 1497 Symptoms ['healthy'] => []
Participant 1312 Symptoms ['healthy'] => []
Participant 2247 Symptoms ['healthy'] => []
Participant 1758 Symptoms ['healthy'] => []
Participant 1119 Symptoms ['healthy'] => []
Participant 1130 Symptoms ['healthy'] => []
Participant 1334 Symptoms ['healthy'] => []
Participant 2408 Symptoms ['healthy'] => []
Participant 2022 Symptoms ['healthy'] => []
Participant 1801 Symptoms ['healthy'] => []
Participant 2180 Symptoms ['healthy'] => []
Participant 431 Symptoms ['healthy'] => []
Participant 2190 Symptoms ['healthy'] => []
Participant 1601 Symptoms ['healthy'] => []
Participant 4522 Symptoms ['healthy'] => []
Participant 1366 Symptoms ['healthy'] => []
Participant 2556 Symptoms ['healthy'] => []
Participant 2557 Symptoms ['healthy'] => []
Participant 1728 Symptoms ['healthy'] => []
Participant 1569 Symptoms ['healthy'] => []
Participant 2270 Symptoms ['healthy'] => []
Participant 321 Symptoms ['healthy'] => []
Participant 2056 Symptoms ['healthy'] => []
Participant 2058 Symptoms ['healthy'] => []
Participant 1838 Symptoms ['healthy'] => []
Participant 2302 Symptoms ['healthy'] => []
Participant 1360 Symptoms ['cough', 'cold'] => ['cough', 'cold']
Participant 63 Symptoms ['healthy'] => []
Participant 1855 Symptoms ['healthy'] => []
Participant 2141 Symptoms ['healthy'] => []
Participant 1490 Symptoms ['healthy'] => []
Participant 1707 Symptoms ['healthy'] => []
Participant 1732 Symptoms ['healthy'] => []
Participant 650 Symptoms ['healthy'] => []
Participant 1847 Symptoms ['cough', 'sore_throat'] => ['cough', 'sore_throat']
Participant 2709 Symptoms ['healthy'] => []
Participant 3431 Symptoms ['healthy'] => []
Participant 1456 Symptoms ['healthy'] => []
Participant 4518 Symptoms ['healthy'] => []
Participant 2447 Symptoms ['healthy'] => []
Participant 2063 Symptoms ['weakness'] => ['weakness']
Participant 84 Symptoms ['healthy'] => []
Participant 1794 Symptoms ['healthy'] => []
Participant 2705 Symptoms ['healthy'] => []
Participant 2280 Symptoms ['healthy'] => []
Participant 2210 Symptoms ['weakness', 'sore_throat', 'vomiting'] => ['weakness', 'sore_throat', 'vomiting']
Participant 4408 Symptoms ['healthy'] => []
Participant 2487 Symptoms ['healthy'] => []
Participant 1344 Symptoms ['healthy'] => []
Participant 1594 Symptoms ['healthy'] => []
Participant 2238 Symptoms ['healthy'] => []
Participant 722 Symptoms ['healthy'] => []
Participant 698 Symptoms ['healthy'] => []
Participant 2126 Symptoms ['healthy'] => []
Participant 1412 Symptoms ['healthy'] => []
Participant 5 Symptoms ['diarrhea'] => ['diarrhea']
Participant 1139 Symptoms ['weakness', 'muscles_pain'] => ['weakness', 'muscles_pain']
Participant 710 Symptoms ['healthy'] => []
Participant 699 Symptoms ['healthy'] => []
Participant 4513 Symptoms ['healthy'] => []
Participant 1815 Symptoms ['healthy'] => []
Participant 761 Symptoms ['healthy'] => []
Participant 2224 Symptoms ['healthy'] => []
Participant 601 Symptoms ['healthy'] => []
Participant 2001 Symptoms ['healthy'] => []
Participant 2811 Symptoms ['healthy'] => []
Participant 2420 Symptoms ['headache', 'weakness', 'vomiting'] => ['headache', 'weakness', 'vomiting']
Participant 1372 Symptoms ['healthy'] => []
Participant 2182 Symptoms ['healthy'] => []
Participant 1802 Symptoms ['healthy'] => []
Participant 239 Symptoms ['healthy'] => []
Participant 137 Symptoms ['healthy'] => []
Participant 1352 Symptoms ['healthy'] => []
Participant 2096 Symptoms ['healthy'] => []
Participant 1562 Symptoms ['healthy'] => []
Participant 1512 Symptoms ['healthy'] => []
Participant 2153 Symptoms ['healthy'] => []
Participant 2272 Symptoms ['healthy'] => []
Participant 1050 Symptoms ['healthy'] => []
Participant 1422 Symptoms ['healthy'] => []
Participant 4529 Symptoms ['headache', 'weakness'] => ['headache', 'weakness']
Participant 1142 Symptoms ['healthy'] => []
Participant 179 Symptoms ['healthy'] => []
Participant 592 Symptoms ['healthy'] => []
Participant 1425 Symptoms ['healthy'] => []
Participant 2826 Symptoms ['healthy'] => []
Participant 1105 Symptoms ['healthy'] => []
Participant 807 Symptoms ['healthy'] => []
Participant 1770 Symptoms ['healthy'] => []
Participant 626 Symptoms ['healthy'] => []
Participant 2178 Symptoms ['healthy'] => []
Participant 2161 Symptoms ['healthy'] => []
Participant 1450 Symptoms ['healthy'] => []
Participant 2488 Symptoms ['muscles_pain'] => ['muscles_pain']
Participant 2234 Symptoms ['headache'] => ['headache']
Participant 152 Symptoms ['healthy'] => []
Participant 154 Symptoms ['healthy'] => []
Participant 2122 Symptoms ['healthy'] => []
Participant 2024 Symptoms ['healthy'] => []
Participant 1867 Symptoms ['healthy'] => []
Participant 728 Symptoms ['healthy'] => []
Participant 1791 Symptoms ['healthy'] => []
Participant 1140 Symptoms ['headache'] => ['headache']
Participant 738 Symptoms ['muscles_pain'] => ['muscles_pain']
Participant 2810 Symptoms ['healthy'] => []

Participant 871 Symptoms ['healthy'] => []
Participant 2510 Symptoms ['healthy'] => []
Participant 2423 Symptoms ['healthy'] => []
Participant 721 Symptoms ['healthy'] => []
Participant 2670 Symptoms ['chills'] => ['chills']
Participant 2816 Symptoms ['healthy'] => []
Participant 2918 Symptoms ['healthy'] => []
Participant 365 Symptoms ['healthy'] => []
Participant 1371 Symptoms ['headache', 'weakness'] => ['headache', 'weakness']
Participant 1514 Symptoms ['sore_throat'] => ['sore_throat']
Participant 2514 Symptoms ['healthy'] => []
Participant 2214 Symptoms ['healthy'] => []
Participant 71 Symptoms ['headache', 'weakness'] => ['headache', 'weakness']
Participant 2036 Symptoms ['weakness'] => ['weakness']
Participant 2518 Symptoms ['healthy'] => []
Participant 2038 Symptoms ['abdominal_pain', 'weakness'] => ['abdominal_pain', 'weakness']
Participant 1641 Symptoms ['healthy'] => []
Participant 2842 Symptoms ['healthy'] => []
Participant 2665 Symptoms ['diarrhea'] => ['diarrhea']
Participant 1734 Symptoms ['healthy'] => []
Participant 1379 Symptoms ['healthy'] => []
Participant 2087 Symptoms ['healthy'] => []
Participant 1433 Symptoms ['healthy'] => []
Participant 2809 Symptoms ['healthy'] => []
Participant 2085 Symptoms ['healthy'] => []
Participant 442 Symptoms ['healthy'] => []
Participant 1810 Symptoms ['healthy'] => []
Participant 2259 Symptoms ['healthy'] => []
Participant 2102 Symptoms ['healthy'] => []
Participant 2595 Symptoms ['healthy'] => []
Participant 2202 Symptoms ['healthy'] => []
Participant 2660 Symptoms ['cold'] => ['cold']
Participant 2848 Symptoms ['healthy'] => []
Participant 2241 Symptoms ['weakness'] => ['weakness']
Participant 745 Symptoms ['healthy'] => []
Participant 1519 Symptoms ['other'] => ['other']
Participant 375 Symptoms ['healthy'] => []
Participant 4427 Symptoms ['abdominal_pain'] => ['abdominal_pain']
Participant 1126 Symptoms ['healthy'] => []
Participant 2912 Symptoms ['healthy'] => []
Participant 1575 Symptoms ['healthy'] => []
Participant 2506 Symptoms ['healthy'] => []
Participant 1637 Symptoms ['cough', 'weakness', 'muscles_pain'] => ['cough', 'weakness', 'muscles_pain']
Participant 1460 Symptoms ['healthy'] => []
Participant 2441 Symptoms ['healthy'] => []
Participant 2577 Symptoms ['healthy'] => []
Participant 844 Symptoms ['healthy'] => []
Participant 848 Symptoms ['healthy'] => []
Participant 2243 Symptoms ['headache'] => ['headache']
Participant 2239 Symptoms ['healthy'] => []
Participant 1385 Symptoms ['healthy'] => []
Participant 1426 Symptoms ['healthy'] => []
Participant 2824 Symptoms ['healthy'] => []
Participant 1895 Symptoms ['healthy'] => []
Participant 2040 Symptoms ['healthy'] => []
Participant 1541 Symptoms ['healthy'] => []
Participant 2159 Symptoms ['healthy'] => []
Participant 2129 Symptoms ['healthy'] => []
Participant 2544 Symptoms ['sore_throat'] => ['sore_throat']
Participant 2055 Symptoms ['healthy'] => []
Participant 1338 Symptoms ['healthy'] => []
Participant 2054 Symptoms ['healthy'] => []
Participant 2035 Symptoms ['healthy'] => []
Participant 2112 Symptoms ['healthy'] => []
Participant 2672 Symptoms ['healthy'] => []
Participant 2410 Symptoms ['healthy'] => []
Participant 1764 Symptoms ['healthy'] => []
Participant 2677 Symptoms ['healthy'] => []
Participant 2678 Symptoms ['healthy'] => []
Participant 2813 Symptoms ['healthy'] => []
Participant 2468 Symptoms ['healthy'] => []
Participant 1590 Symptoms ['other'] => ['other']
Participant 2924 Symptoms ['headache'] => ['headache']
Participant 2204 Symptoms ['healthy'] => []
Participant 4435 Symptoms ['cough', 'cold', 'weakness', 'sore_throat'] => ['cough', 'cold', 'weakness', 'sore_throat']
Participant 4514 Symptoms ['healthy'] => []
Participant 630 Symptoms ['healthy'] => []
Participant 1646 Symptoms ['healthy'] => []
Participant 2903 Symptoms ['healthy'] => []
Participant 2850 Symptoms ['healthy'] => []
Participant 1848 Symptoms ['healthy'] => []
Participant 2592 Symptoms ['healthy'] => []
Participant 2836 Symptoms ['headache', 'weakness'] => ['headache', 'weakness']
Participant 1536 Symptoms ['healthy'] => []
Participant 2687 Symptoms ['healthy'] => []
Participant 2481 Symptoms ['healthy'] => []
Participant 2575 Symptoms ['healthy'] => []
Participant 1168 Symptoms ['healthy'] => []
Participant 737 Symptoms ['healthy'] => []
Participant 1159 Symptoms ['healthy'] => []
Participant 2482 Symptoms ['healthy'] => []
Participant 2106 Symptoms ['weakness', 'sore_throat'] => ['weakness', 'sore_throat']
Participant 1900 Symptoms ['healthy'] => []
Participant 2309 Symptoms ['healthy'] => []
Participant 1652 Symptoms ['healthy'] => []
Participant 2846 Symptoms ['healthy'] => []
Participant 1383 Symptoms ['cough', 'cold', 'headache'] => ['cough', 'cold', 'headache']
Participant 1731 Symptoms ['healthy'] => []
Participant 2838 Symptoms ['healthy'] => []
Participant 2416 Symptoms ['healthy'] => []
Participant 2198 Symptoms ['healthy'] => []
Participant 1755 Symptoms ['healthy'] => []
Participant 2442 Symptoms ['headache', 'cold', 'weakness', 'sore_throat'] => ['headache', 'cold', 'weakness', 'sore_throat']
Participant 1839 Symptoms ['healthy'] => []
Participant 2655 Symptoms ['healthy'] => []
Participant 1849 Symptoms ['healthy'] => []
Participant 2268 Symptoms ['diarrhea'] => ['diarrhea']
Participant 2681 Symptoms ['healthy'] => []
Participant 1459 Symptoms ['healthy'] => []
Participant 2034 Symptoms ['healthy'] => []
Participant 1226 Symptoms ['weakness'] => ['weakness']
Participant 2675 Symptoms ['healthy'] => []
Participant 1657 Symptoms ['healthy'] => []
Participant 1616 Symptoms ['healthy'] => []
Participant 2671 Symptoms ['healthy'] => []
Participant 2193 Symptoms ['healthy'] => []
Participant 1496 Symptoms ['healthy'] => []
Participant 2572 Symptoms ['healthy'] => []
Participant 95 Symptoms ['healthy'] => []
Participant 1793 Symptoms ['headache', 'vomiting'] => ['headache', 'vomiting']
Participant 2486 Symptoms ['healthy'] => []
Participant 2472 Symptoms ['healthy'] => []
Participant 2857 Symptoms ['headache'] => ['headache']
Participant 4507 Symptoms ['healthy'] => []
Participant 2517 Symptoms ['healthy'] => []
Participant 2565 Symptoms ['healthy'] => []
Participant 1775 Symptoms ['healthy'] => []
Participant 1341 Symptoms ['healthy'] => []
Participant 1515 Symptoms ['headache', 'weakness', 'muscles_pain'] => ['headache', 'weakness', 'muscles_pain']
Participant 1860 Symptoms ['healthy'] => []
Participant 2256 Symptoms ['healthy'] => []
Participant 2935 Symptoms ['healthy'] => []
Participant 1295 Symptoms ['healthy'] => []
Participant 2455 Symptoms ['healthy'] => []
Participant 2086 Symptoms ['healthy'] => []
Participant 2110 Symptoms ['healthy'] => []
Participant 4006 Symptoms ['weakness'] => ['weakness']
Participant 1593 Symptoms ['healthy'] => []
Participant 2287 Symptoms ['healthy'] => []
Participant 1409 Symptoms ['healthy'] => []
Participant 2832 Symptoms ['healthy'] => []
Participant 2267 Symptoms ['healthy'] => []
Participant 1402 Symptoms ['healthy'] => []
Participant 2158 Symptoms ['healthy'] => []
Participant 2188 Symptoms ['healthy'] => []
Participant 1487 Symptoms ['healthy'] => []
Participant 2570 Symptoms ['healthy'] => []
Participant 2511 Symptoms ['healthy'] => []
Participant 605 Symptoms ['healthy'] => []
Participant 2151 Symptoms ['sore_throat'] => ['sore_throat']
Participant 1612 Symptoms ['healthy'] => []
Participant 2418 Symptoms ['healthy'] => []
Participant 1633 Symptoms ['healthy'] => []
Participant 4412 Symptoms ['healthy'] => []
Participant 1353 Symptoms ['healthy'] => []
Participant 1393 Symptoms ['healthy'] => []
Participant 209 Symptoms ['healthy'] => []
Participant 2467 Symptoms ['healthy'] => []
Participant 1739 Symptoms ['healthy'] => []
Participant 2091 Symptoms ['healthy'] => []
Participant 2523 Symptoms ['healthy'] => []
Participant 2923 Symptoms ['healthy'] => []
Participant 1808 Symptoms ['healthy'] => []
Participant 2620 Symptoms ['healthy'] => []
Participant 2220 Symptoms ['healthy'] => []
Participant 2901 Symptoms ['healthy'] => []
Participant 1288 Symptoms ['healthy'] => []
Participant 2143 Symptoms ['healthy'] => []
Participant 2191 Symptoms ['healthy'] => []
Participant 2961 Symptoms ['healthy'] => []
Participant 654 Symptoms ['weakness'] => ['weakness']
Participant 2427 Symptoms ['healthy'] => []
Participant 2938 Symptoms ['healthy'] => []
Participant 2604 Symptoms ['healthy'] => []
Participant 1897 Symptoms ['healthy'] => []
Participant 2823 Symptoms ['headache', 'weakness'] => ['headache', 'weakness']
Participant 1702 Symptoms ['healthy'] => []
Participant 2941 Symptoms ['healthy'] => []
Participant 2257 Symptoms ['healthy'] => []
Participant 181 Symptoms ['healthy'] => []
Participant 2135 Symptoms ['healthy'] => []
Participant 2131 Symptoms ['healthy'] => []
Participant 2697 Symptoms ['healthy'] => []
Participant 2264 Symptoms ['healthy'] => []
Participant 1812 Symptoms ['muscles_pain'] => ['muscles_pain']
Participant 2931 Symptoms ['healthy'] => []
Participant 640 Symptoms ['healthy'] => []
Participant 2939 Symptoms ['healthy'] => []
Participant 1603 Symptoms ['healthy'] => []
Participant 2966 Symptoms ['healthy'] => []
Participant 2043 Symptoms ['healthy'] => []
Participant 1362 Symptoms ['healthy'] => []
Participant 1483 Symptoms ['healthy'] => []
Participant 2706 Symptoms ['healthy'] => []
Participant 2866 Symptoms ['healthy'] => []
Participant 2453 Symptoms ['healthy'] => []
Participant 591 Symptoms ['healthy'] => []
Participant 2623 Symptoms ['weakness'] => ['weakness']
Participant 2552 Symptoms ['healthy'] => []
Participant 2132 Symptoms ['headache', 'weakness'] => ['headache', 'weakness']
Participant 1706 Symptoms ['healthy'] => []
Participant 3432 Symptoms ['healthy'] => []
Participant 1401 Symptoms ['healthy'] => []
Participant 2699 Symptoms ['healthy'] => []
Participant 2650 Symptoms ['abdominal_pain'] => ['abdominal_pain']
Participant 2559 Symptoms ['healthy'] => []
Participant 1776 Symptoms ['healthy'] => []
Participant 1730 Symptoms ['healthy'] => []
Participant 1363 Symptoms ['healthy'] => []
Participant 2907 Symptoms ['cough', 'cold'] => ['cough', 'cold']
Participant 2959 Symptoms ['healthy'] => []
Participant 454 Symptoms ['healthy'] => []
Participant 1816 Symptoms ['healthy'] => []
Participant 2654 Symptoms ['healthy'] => []
Participant 2647 Symptoms ['healthy'] => []
Participant 1485 Symptoms ['healthy'] => []
Participant 1889 Symptoms ['healthy'] => []
Participant 2521 Symptoms ['healthy'] => []
Participant 1743 Symptoms ['healthy'] => []
Participant 2088 Symptoms ['weakness'] => ['weakness']
Participant 2499 Symptoms ['weakness', 'other'] => ['weakness', 'other']
Participant 2535 Symptoms ['healthy'] => []
Participant 2878 Symptoms ['healthy'] => []
Participant 1452 Symptoms ['healthy'] => []
Participant 2598 Symptoms ['healthy'] => []
Participant 2986 Symptoms ['cough', 'cold', 'weakness'] => ['cough', 'cold', 'weakness']
Participant 2026 Symptoms ['healthy'] => []
Participant 2827 Symptoms ['headache'] => ['headache']
Participant 2009 Symptoms ['healthy'] => []
Participant 2113 Symptoms ['healthy'] => []
Participant 2451 Symptoms ['healthy'] => []
Participant 2288 Symptoms ['healthy'] => []
Participant 2016 Symptoms ['healthy'] => []
Participant 1513 Symptoms ['healthy'] => []
Participant 1645 Symptoms ['healthy'] => []
Participant 3000 Symptoms ['healthy'] => []
Participant 2515 Symptoms ['healthy'] => []
Participant 2192 Symptoms ['headache', 'weakness'] => ['headache', 'weakness']
Participant 2503 Symptoms ['healthy'] => []
Participant 2081 Symptoms ['healthy'] => []
Participant 2599 Symptoms ['healthy'] => []
Participant 1390 Symptoms ['healthy'] => []
Participant 2716 Symptoms ['healthy'] => []
Participant 1714 Symptoms ['weakness'] => ['weakness']
Participant 2228 Symptoms ['healthy'] => []
Participant 847 Symptoms ['healthy'] => []
Participant 2261 Symptoms ['cold', 'weakness', 'sore_throat'] => ['cold', 'weakness', 'sore_throat']
Participant 2627 Symptoms ['healthy'] => []
Participant 1337 Symptoms ['healthy'] => []
Participant 1194 Symptoms ['headache', 'weakness', 'muscles_pain'] => ['headache', 'weakness', 'muscles_pain']
Participant 1729 Symptoms ['healthy'] => []
Participant 2493 Symptoms ['healthy'] => []
Participant 435 Symptoms ['healthy'] => []
Participant 2095 Symptoms ['healthy'] => []
Participant 1308 Symptoms ['healthy'] => []
Participant 2149 Symptoms ['healthy'] => []
Participant 2114 Symptoms ['healthy'] => []
Participant 2549 Symptoms ['healthy'] => []
Participant 2555 Symptoms ['healthy'] => []
Participant 1580 Symptoms ['healthy'] => []
Participant 2221 Symptoms ['muscles_pain'] => ['muscles_pain']
Participant 1809 Symptoms ['healthy'] => []
Participant 2215 Symptoms ['headache', 'weakness', 'muscles_pain', 'feel_heat'] => ['headache', 'weakness', 'muscles_pain', 'feel_heat']
Participant 2621 Symptoms ['healthy'] => []
Participant 2222 Symptoms ['cough', 'headache', 'sore_throat', 'chills', 'weakness', 'muscles_pain'] => ['cough', 'headache', 'sore_throat', 'chills', 'weakness', 'muscles_pain']
Participant 2093 Symptoms ['healthy'] => []
Participant 2260 Symptoms ['healthy'] => []
Participant 2242 Symptoms ['healthy'] => []
Participant 2642 Symptoms ['healthy'] => []
Participant 2047 Symptoms ['headache'] => ['headache']
Participant 2634 Symptoms ['healthy'] => []
Participant 2138 Symptoms ['cold'] => ['cold']
Participant 2806 Symptoms ['healthy'] => []
Participant 1650 Symptoms ['healthy'] => []
Participant 1509 Symptoms ['healthy'] => []
Participant 4409 Symptoms ['healthy'] => []
Participant 2637 Symptoms ['healthy'] => []
Participant 2594 Symptoms ['healthy'] => []
Participant 2849 Symptoms ['healthy'] => []
Participant 169 Symptoms ['healthy'] => []
Participant 1738 Symptoms ['healthy'] => []
Participant 2985 Symptoms ['healthy'] => []
Participant 2972 Symptoms ['healthy'] => []
Participant 2680 Symptoms ['healthy'] => []
Participant 1436 Symptoms ['cough', 'weakness', 'muscles_pain'] => ['cough', 'weakness', 'muscles_pain']
Participant 1396 Symptoms ['healthy'] => []
Participant 2566 Symptoms ['healthy'] => []
Participant 2444 Symptoms ['healthy'] => []
Participant 2053 Symptoms ['cough', 'cold', 'weakness'] => ['cough', 'cold', 'weakness']
Participant 1423 Symptoms ['healthy'] => []
Participant 2436 Symptoms ['healthy'] => []
Participant 1700 Symptoms ['healthy'] => []
Participant 1892 Symptoms ['healthy'] => []
Participant 2579 Symptoms ['healthy'] => []
Participant 4406 Symptoms ['healthy'] => []
Participant 2457 Symptoms ['healthy'] => []
Participant 1531 Symptoms ['healthy'] => []
Participant 1240 Symptoms ['abdominal_pain'] => ['abdominal_pain']
Participant 1449 Symptoms ['healthy'] => []
Participant 1431 Symptoms ['healthy'] => []
Participant 221 Symptoms ['healthy'] => []
Participant 2508 Symptoms ['healthy'] => []
Participant 2240 Symptoms ['healthy'] => []
Participant 1502 Symptoms ['weakness'] => ['weakness']
Participant 2459 Symptoms ['healthy'] => []
Participant 2852 Symptoms ['healthy'] => []
Participant 1887 Symptoms ['healthy'] => []
Participant 2651 Symptoms ['healthy'] => []
Participant 1413 Symptoms ['healthy'] => []
Participant 2297 Symptoms ['healthy'] => []
Participant 1444 Symptoms ['healthy'] => []
Participant 2062 Symptoms ['healthy'] => []
Participant 2184 Symptoms ['healthy'] => []
Participant 1643 Symptoms ['healthy'] => []
Participant 1361 Symptoms ['weakness'] => ['weakness']
Participant 2877 Symptoms ['cold'] => ['cold']
Participant 2870 Symptoms ['healthy'] => []
Participant 1527 Symptoms ['healthy'] => []
Participant 2424 Symptoms ['cough', 'cold', 'headache'] => ['cough', 'cold', 'headache']
Participant 1484 Symptoms ['healthy'] => []
Participant 2157 Symptoms ['healthy'] => []
Participant 1879 Symptoms ['healthy'] => []
Participant 1722 Symptoms ['healthy'] => []
Participant 2068 Symptoms ['healthy'] => []
Participant 2065 Symptoms ['healthy'] => []
Participant 232 Symptoms ['healthy'] => []
Participant 2251 Symptoms ['healthy'] => []
Participant 2186 Symptoms ['muscles_pain'] => ['muscles_pain']
Participant 709 Symptoms ['healthy'] => []
Participant 2825 Symptoms ['healthy'] => []
Participant 1386 Symptoms ['healthy'] => []
Participant 685 Symptoms ['healthy'] => []
Participant 2498 Symptoms ['healthy'] => []
Participant 2147 Symptoms ['healthy'] => []
Participant 629 Symptoms ['healthy'] => []
Participant 2306 Symptoms ['healthy'] => []
Participant 1156 Symptoms ['healthy'] => []
Participant 2597 Symptoms ['healthy'] => []
Participant 801 Symptoms ['healthy'] => []
Participant 2648 Symptoms ['healthy'] => []
Participant 1904 Symptoms ['healthy'] => []
Participant 92 Symptoms ['headache', 'dyspnea', 'muscles_pain', 'confusion'] => ['headache', 'dyspnea', 'muscles_pain', 'confusion']
Participant 1627 Symptoms ['healthy'] => []
Participant 2223 Symptoms ['healthy'] => []
Participant 2676 Symptoms ['healthy'] => []
Participant 2046 Symptoms ['healthy'] => []
Participant 2708 Symptoms ['healthy'] => []
Participant 309 Symptoms ['healthy'] => []
Participant 2263 Symptoms ['cough', 'cold', 'weakness'] => ['cough', 'cold', 'weakness']
Participant 2072 Symptoms ['healthy'] => []
Participant 2858 Symptoms ['healthy'] => []
Participant 2064 Symptoms ['cough', 'dyspnea'] => ['cough', 'dyspnea']
Participant 1333 Symptoms ['headache', 'weakness', 'muscles_pain', 'sore_throat'] => ['headache', 'weakness', 'muscles_pain', 'sore_throat']
Participant 1557 Symptoms ['healthy'] => []
Participant 1611 Symptoms ['healthy'] => []
Participant 2713 Symptoms ['healthy'] => []
Participant 2635 Symptoms ['healthy'] => []
Participant 2958 Symptoms ['healthy'] => []
Participant 1486 Symptoms ['weakness', 'confusion'] => ['weakness', 'confusion']
Participant 2173 Symptoms ['healthy'] => []
Participant 2701 Symptoms ['headache'] => ['headache']
Participant 2429 Symptoms ['healthy'] => []
Participant 2502 Symptoms ['healthy'] => []
Participant 1653 Symptoms ['healthy'] => []
Participant 1492 Symptoms ['healthy'] => []
Participant 600 Symptoms ['healthy'] => []
Participant 845 Symptoms ['weakness', 'muscles_pain'] => ['weakness', 'muscles_pain']
Participant 2532 Symptoms ['healthy'] => []
Participant 1712 Symptoms ['healthy'] => []
Participant 2464 Symptoms ['healthy'] => []
Participant 2965 Symptoms ['healthy'] => []
Participant 165 Symptoms ['healthy'] => []
Participant 1376 Symptoms ['healthy'] => []
Participant 2979 Symptoms ['healthy'] => []
Participant 2711 Symptoms ['healthy'] => []
Participant 2844 Symptoms ['healthy'] => []
Participant 2019 Symptoms ['healthy'] => []
Participant 2414 Symptoms ['healthy'] => []
Participant 2490 Symptoms ['healthy'] => []
Participant 2117 Symptoms ['healthy'] => []
Participant 2550 Symptoms ['healthy'] => []
Participant 3114 Symptoms ['healthy'] => []
Participant 908 Symptoms ['healthy'] => []
Participant 1526 Symptoms ['healthy'] => []
Participant 826 Symptoms ['healthy'] => []
Participant 3109 Symptoms ['healthy'] => []
Participant 1753 Symptoms ['healthy'] => []
Participant 2551 Symptoms ['muscles_pain'] => ['muscles_pain']
Participant 392 Symptoms ['healthy'] => []
Participant 4323 Symptoms ['other'] => ['other']
Participant 676 Symptoms ['sore_throat', 'vomiting', 'chills', 'weakness', 'muscles_pain', 'feel_heat'] => ['sore_throat', 'vomiting', 'chills', 'weakness', 'muscles_pain', 'feel_heat']
Participant 2527 Symptoms ['healthy'] => []
Participant 1346 Symptoms ['healthy'] => []
Participant 2226 Symptoms ['healthy'] => []
Participant 1418 Symptoms ['healthy'] => []
Participant 2605 Symptoms ['healthy'] => []
Participant 488 Symptoms ['healthy'] => []
Participant 2229 Symptoms ['healthy'] => []
Participant 425 Symptoms ['healthy'] => []
Participant 2028 Symptoms ['healthy'] => []
Participant 2831 Symptoms ['healthy'] => []

In [24]:
for part_to_sbv_dict in part_to_sbv_dicts:
    print(len(part_to_sbv_dict.keys()))

216
343
1327

In [25]:
severe_symptoms = ['chest_pain', 'dyspnea', 'heat over 38.9', 'confusion', 'chills']

In [26]:
# Get Healthy and Sick Participant Numbers

def create_healthy_sick_participant_arrays(vaccine_num):
    participant_num_to_symptoms = dict()
    days_since_vaccine = vaccines_to_analyze[vaccine_num]
    vaccine_label = vaccine_labels[vaccine_num]
    symptoms_df = symptoms_dfs[vaccine_num]
    part_to_symptoms_before_vaccine = part_to_sbv_dicts[vaccine_num]

    severe_participants = list()
    mild_participants = list()
    healthy_participants = list()
    all_participants = list()
    missing_day_before_vaccine_participants = list()

    df = symptoms_df.where(symptoms_df[days_since_vaccine]>=0).where(symptoms_df[days_since_vaccine]<=2).dropna(how='all')

    symptoms_list = list()
    for i,r in df.iterrows():
        symptoms_old = r["quest_symptoms_processed"].split(',')
        symptoms = preprocess_symptom_array(symptoms_old)

        participant = r["participant_num"]
        
        # If they don't have data from the day before the vaccine, we won't be able to tell
        # if their symptoms are new from the vaccine or not.
        # I exclude healthy people who did not fill out the form the day before the vaccine
        # as to not bias the findings to include those who were healthy.
        try:
            symptoms_before_vaccine = part_to_symptoms_before_vaccine[participant]

            if symptoms == [''] or symptoms == ['skipped_question'] or symptoms == ['-1']:
                # Participants who skipped the questionnaire after the vaccine get skipped.
                pass
            elif 'healthy' in symptoms or symptoms == ['no heat']:
                # Healthy participants just get added to all_participants
                try:
                    participant_num_to_symptoms[participant]
                except:
                    participant_num_to_symptoms[participant] = list()
                    all_participants.append(participant)
            else:
                # Iterate through all of the symptoms and classify the new ones into
                # Severe and Mild reactions.
                for s in symptoms:
                    if s in possible_symptoms and s != '' and s != 'no heat':
                        if s not in symptoms_before_vaccine:
                            if s in severe_symptoms:
                                severe_participants.append(participant)
                            else:
                                mild_participants.append(participant)
                            # Add the new symptom to the list of symptoms
                            try:
                                participant_num_to_symptoms[participant].append(s)
                            except:
                                participant_num_to_symptoms[participant] = list()
                                participant_num_to_symptoms[participant].append(s)
                                all_participants.append(participant)
                        else:
                            # Participant with no new symptoms just get added to all_participants
                            try:
                                participant_num_to_symptoms[participant]
                            except:
                                participant_num_to_symptoms[participant] = list()
                                all_participants.append(participant)
        except:
            missing_day_before_vaccine_participants.append(participant)
            
    
    for k, v in participant_num_to_symptoms.items():
        if len(v) == 0:
            participant_num_to_symptoms[k] = ['healthy'] 
        else:
            participant_num_to_symptoms[k] = list(set(v))
            
                        

    # Generate healthy participants by excluding sick participant from all participants we have data for
    severe_participants = list(set(severe_participants))
    mild_participants = list(set(mild_participants))
    mild_participants = [part for part in mild_participants if part not in severe_participants]
    all_participants = list(set(all_participants))
    print("%s Severe Participant Numbers: %s" % (vaccine_label, severe_participants))
    print("%s Mild Participant Numbers: %s" % (vaccine_label, mild_participants))
    healthy_participants = [part for part in all_participants if part not in severe_participants and part not in mild_participants]
    
    assert(set(severe_participants).isdisjoint(mild_participants))
    assert(set(severe_participants).isdisjoint(healthy_participants))
    assert(set(mild_participants).isdisjoint(healthy_participants))
    assert(set(all_participants).isdisjoint(missing_day_before_vaccine_participants))
    
    print("Severe n=%d\tMild n=%d\tHealthy n=%d\tAll n=%d\tMissing n=%d" % (len(severe_participants),
                                                                            len(mild_participants),
                                                              len(healthy_participants),
                                                              len(all_participants),
                                                              len(missing_day_before_vaccine_participants)))
    
    return severe_participants, mild_participants, healthy_participants, all_participants, missing_day_before_vaccine_participants, participant_num_to_symptoms

In [27]:

#First Vaccination Severe Participant Numbers: ['63', '1108', '137', '198', 'p1_223', 'p1_8', '68', '36']
#First Vaccination Mild Participant Numbers: ['187', 'p1_17', 'p1_255', '169', '53', 'p1_400', '85', '153', '99', '161', '557', 'p1_561', '93', '32', '118', '73', 'p1_154', '41', '48', 'p1_237', '230', 'p1_20', '329', '28', '50', '119', 'p1_606', '136', '49', 'p1_590', 'p1_211']
#Severe n=8	Mild n=31	Healthy n=154	All n=193	Missing n=27

v1severe, v1mild, v1healthy, v1all, v1missing, v1participant_num_to_symptoms = create_healthy_sick_participant_arrays(0)
v2severe, v2mild, v2healthy, v2all, v2missing, v2participant_num_to_symptoms = create_healthy_sick_participant_arrays(1)
v3severe, v3mild, v3healthy, v3all, v3missing, v3participant_num_to_symptoms = create_healthy_sick_participant_arrays(2)

First Vaccination Severe Participant Numbers: ['1108', '137', '198', 'p1_8', '68', '36']
First Vaccination Mild Participant Numbers: ['p1_400', '53', '85', '153', 'p1_539', '230', '187', '169', '32', 'p1_20', 'p1_32', 'p1_17', 'p1_223', '49', '118', '119', '41', '48', '136', 'p1_606', '99', 'p1_154', 'p1_590', '557', '28', '161', 'p1_211', 'p1_237', '329', 'p1_244', '50', 'p1_561', '73', '93']
Severe n=6	Mild n=34	Healthy n=164	All n=204	Missing n=25
Second Vaccination Severe Participant Numbers: ['p1_634', 'p1_642', 'p1_551', 'p1_616', 'p1_204', 'p1_8', 'p1_614', '169', 'p1_3', '32', 'p1_522', 'p1_595', 'p1_584', 'p1_16', 'p1_525', '49', 'p1_536', '24', 'p1_615', 'p1_622', '103', 'p1_600', 'p1_4', '48', 'p1_577', '136', 'p1_509', '18', '99', '54', 'p1_501', 'p1_553', 'p1_629', 'p1_597', 'p1_303', '161', 'p1_403', 'p1_515', '21', 'p1_113', '603', 'p1_618', 'p1_244', 'p1_549', '50', 'p1_592', 'p1_617', 'p1_550', 'p1_547', '163', 'p1_588', 'p1_559']
Second Vaccination Mild Participant Numbers: ['p1_533', 'p1_566', 'p1_542', '147', 'p1_628', '56', 'p1_413', 'p1_641', 'p1_287', 'p1_298', 'p1_606', '201', 'p1_563', 'p1_211', 'p1_545', 'p1_401', 'p1_647', 'p1_627', '1298', '93', 'p1_406', '85', 'p1_226', 'p1_565', 'p1_586', 'p1_546', '25', 'p1_510', '221', 'p1_604', 'p1_17', 'p1_255', '309', 'p1_276', 'p1_412', '36', 'p1_638', 'p1_636', 'p1_599', 'p1_154', 'p1_585', 'p1_521', '57', 'p1_237', '329', 'p1_645', 'p1_554', 'p1_620', '323', '73', '162', 'p1_539', '109', 'p1_518', 'p1_206', 'p1_32', 'p1_530', 'p1_649', '274', 'p1_414', 'p1_621', 'p1_632', 'p1_516', 'p1_238', 'p1_572', 'p1_507', '154', '137', '92', 'p1_265', 'p1_777', 'p1_596', 'p1_574', 'p1_564', '70', 'p1_650', 'p1_118', 'p1_502', '192', '89', 'p1_527', 'p1_33', '160', 'p1_613', 'p1_630', 'p1_575', '210', 'p1_137', 'p1_646', '4', 'p1_543', 'p1_25', '155', 'p1_535', 'p1_635', 'p1_582', 'p1_514', '104', 'p1_567', 'p1_608', '198', 'p1_594']
Severe n=52	Mild n=102	Healthy n=181	All n=335	Missing n=63
Third Vaccination Severe Participant Numbers: ['2193', '1390', '517', '679', '2650', '2256', '317', '2634', '1776', '740', '2021', '2227', '32', '402', '2523', '339', '1569', '2242', '2588', '1882', '2069', '2285', '1325', '822', '1271', '2132', '1558', '1869', '2128', '2084', '239', '2228', '1213', '163', '829', '1496', '2260', '2243', '1446', '1143', '1646', '2651', '1802', '1810', '2138', '251', '1581', '2660', '1719', '2215', '1109', '447', '1483', '2442', '1194', '811', '421', '2706', '1731', '468', '832', '1557', '454', '1758', '1627', '1226', '1893', '2605', '554', '2959', '2190', '2827', '2143', '1300', '2047', '1458', '2297', '654', '1130', '1220', '2087', '2488', '2495', '18', '2487', '570', '2532', '2935', '450', '50', '1452', '579', '494', '659', '2124', '2623', '2153', '1144', '628', '2931', '2420', '2459', '479', '805', '2074', '2809', '502', '1244', '1147', '2022', '2824', '808', '2647', '1129', '2192', '1201', '2261', '1486', '708', '2107']
Third Vaccination Mild Participant Numbers: ['4102', '1178', '2058', '1764', '4323', '1240', '2082', '1774', '2129', '2526', '1206', '1876', '4103', '546', '2064', '295', '753', '1298', '2252', '351', '277', '448', '732', '1515', '2515', '1855', '1361', '827', '2016', '1257', '2585', '2299', '2117', '606', '1872', '99', '1892', '1856', '1528', '712', '2810', '2857', '1383', '2408', '2878', '1822', '1801', '1612', '1450', '63', '1339', '2148', '1128', '2206', '1565', '2035', '24', '1273', '1640', '1169', '605', '1139', '1849', '2241', '2409', '1154', '1306', '114', '2418', '601', '844', '152', '2670', '2709', '1333', '2852', '763', '2549', '2671', '2556', '1541', '1519', '210', '2222', '725', '1523', '1441', '1110', '1295', '2642', '116', '1346', '1440', '1426', '2065', '2280', '23', '1235', '1873', '2594', '2713', '549', '2826', '2024', '564', '555', '1445', '4506', '2036', '1161', '1583', '1379', '1280', '1848', '1645', '54', '866', '742', '1702', '1791', '1875', '2114', '2126', '2631', '2569', '1427', '2609', '2062', '736', '1371', '2567', '2557', '894', '2877', '2708', '4898', '2056', '2210', '1241', '309', '1425', '2303', '1342', '1251', '2238', '96', '310', '2023', '413', '2111', '728', '2217', '2309', '2846', '868', '76', '292', '1337', '252', '1643', '1364', '2248', '478', '1757', '137', '860', '92', '1739', '1593', '2213', '2407', '2697', '644', '1487', '1394', '1374', '1809', '2112', '41', '120', '1861', '48', '729', '136', '2416', '2178', '1448', '191', '437', '572', '2179', '4600', '2482', '688', '2214', '2184', '1315', '475', '833', '2441', '2457', '2173', '759', '1310', '749', '46', '1132', '1512', '1367', '4503', '1611', '4202', '665', '2635', '2234', '646', '2046', '1657', '2493', '770', '2665', '2965', '1511', '1889', '325', '1829', '2680', '1232', '863', '2985', '845', '2681', '2240', '670', '1313', '580', '2646', '2579', '625', '586', '1116', '1145', '2520', '2151', '1372', '2182', '847', '318', '1644', '2535', '1200', '418', '73', '1423', '1155', '2494', '2572', '1182', '2279', '733', '750', '2643', '2009', '2508', '662', '1327', '716', '1105', '2436', '2127', '1518', '477', '470', '2095', '281', '1469', '1330', '1548', '2135', '2028', '1650', '183', '1655', '2849', '2287', '1502', '2858', '2267', '2', '1401', '598', '1338', '2272', '2164', '2264', '1320', '2507', '287', '1142', '1344', '2088', '2511', '483', '2306', '503', '2423', '2405', '2185', '855', '1782', '1141', '385', '2152', '1901', '505', '1402', '1140', '1409', '4329', '2085', '1629', '615', '85', '1126', '2848', '1238', '2510', '2445', '676', '2499', '515', '1656', '2716', '1396', '2447', '1157', '161', '2038', '2308', '2401', '2187', '1136', '2509', '1119', '896', '2432', '2540', '1156', '812', '2443', '67', '209', '2598', '2570', '2093', '1484', '3431', '2125', '862', '1158', '856', '1419', '637', '2429', '643', '2802', '1748', '2923', '461', '2106', '1412', '2504', '2842', '2632', '2503', '807', '800', '1228', '2562', '1706', '1592', '1239', '2458', '1050', '2864', '4', '2451', '2490', '2147', '186', '1118', '801', '2091', '1746', '2502', '1637', '2052', '149', '889', '1811', '1805', '1763', '2806', '2086']
Severe n=120	Mild n=404	Healthy n=655	All n=1179	Missing n=94

In [28]:
v1_participant_nums = [v1severe, v1mild, v1healthy, v1all, v1missing]
v2_participant_nums = [v2severe, v2mild, v2healthy, v2all, v2missing]
v3_participant_nums = [v3severe, v3mild, v3healthy, v3all, v3missing]

with open('v1_participant_nums.pkl', 'wb') as f:
    pkl.dump(v1_participant_nums, f)
    
with open('v2_participant_nums.pkl', 'wb') as f:
    pkl.dump(v2_participant_nums, f)
    
with open('v3_participant_nums.pkl', 'wb') as f:
    pkl.dump(v3_participant_nums, f)
    
with open('v1_participant_nums_to_symptoms.pkl', 'wb') as f:
    pkl.dump(v1participant_num_to_symptoms, f)
    
with open('v2_participant_nums_to_symptoms.pkl', 'wb') as f:
    pkl.dump(v2participant_num_to_symptoms, f)
    
with open('v3_participant_nums_to_symptoms.pkl', 'wb') as f:
    pkl.dump(v3participant_num_to_symptoms, f)